/**
  Plusone : generated by hxtern
*/
package gapi;
@:native("gapi.plusone")
extern class Plusone {
	public static function go(?opt_container: js.html.Element): Void {}

	public static function render(id: Hxtern.Any2<js.html.Element,String>, params: Dynamic): Void {}
}
