/**
  WindSpeedUnit : generated by hxtern
*/
package google.maps.weather;

extern class WindSpeedUnit {
	public static var KILOMETERS_PER_HOUR: Dynamic;

	public static var METERS_PER_SECOND: Dynamic;

	public static var MILES_PER_HOUR: Dynamic;
}
