/**
  _gaq : generated by hxtern
*/
package ;

class _gaq{
	public static function _createAsyncTracker(accountId: String, ?opt_name: String): _ga_tracker;

	public static function _getAsyncTracker(?opt_name: String): _ga_tracker;

	public static function push(?_opt0: Void->Void, ?_opt1: Void->Void, ?_opt2: Void->Void, ?_opt3: Void->Void, ?_opt4: Void->Void, ?_opt5: Void->Void): Float;
}
