/**
  _gaq : generated by hxtern
*/
package ;

class _gaq{
	public static function _createAsyncTracker(accountId: String, ?opt_name: String): _ga_tracker;

	public static function _getAsyncTracker(?opt_name: String): _ga_tracker;

	public static function push(?_opt0: Dynamic, ?_opt1: Dynamic, ?_opt2: Dynamic, ?_opt3: Dynamic, ?_opt4: Dynamic, ?_opt5: Dynamic): Float;
}
