/**
  Gat : generated by hxtern
*/
package ;
@:native("_gat")
extern class Gat{
	public static function _anonymizeIp(): Null<Dynamic> {}

	public static function _createTracker(?opt_account: String, ?opt_name: String): Ga_tracker {}

	public static function _getTracker(account: String): Ga_tracker {}

	public static function _getTrackerByName(?opt_name: String): Ga_tracker {}
}
