/**
  Json : generated by hxtern
*/
package gadgets;
@:native("gadgets.json")
extern class Json{
	public static function parse(s: String): Dynamic {}

	public static function stringify(json: Dynamic): String {}
}
