/**
Prefs : generated by hxtern
Class providing access to user preferences, module dimensions, and messages.
*/
package gadgets;

class Prefs{
	public function new(?opt_moduleId: String);

	public function getArray(key: String): Array<String>;

	public function getBool(key: String): Bool;

	public function getCountry(): String;

	public function getFloat(key: String): Float;

	public function getInt(key: String): Float;

	public function getLang(): String;

	public function getModuleId(): Float;

	public function getMsg(key: String): String;

	public function getString(key: String): String;

	public function set(key: String, value: Dynamic): Void;

	public function setArray(key: String, array: Array<String>): Void;
}
