/**
  Util : generated by hxtern
*/
package gadgets;
@:native("gadgets.util")
class Util{
	public static function attachBrowserEvent(elem: Dynamic, eventName: String, _callback: Void->Void, useCapture: Bool): Void {}

	public static function createElement(tagName: String): js.html.Element {}

	public static function createIframeElement(?opt_attribs: Dynamic): js.html.Element {}

	public static function escapeString(str: String): String {}

	public static function getBodyElement(): js.html.Element {}

	public static function getFeatureParameters(feature: String): Dynamic {}

	public static function getUrlParameters(?opt_url: String): Dynamic {}

	public static function hasFeature(feature: String): Bool {}

	public static function makeClosure(scope: Dynamic, _callback: Dynamic, ?_opt0: Dynamic, ?_opt1: Dynamic, ?_opt2: Dynamic, ?_opt3: Dynamic, ?_opt4: Dynamic, ?_opt5: Dynamic): Void {}

	public static function registerOnLoadHandler(fn: Void->Void): Void {}

	public static function unescapeString(str: String): String {}
}
