/**
  Views : generated by hxtern
*/
package gadgets;
@:native("gadgets.views")
class Views{
	public static function getCurrentView(): gadgets.views.View;

	public static function getParams(): Dynamic;

	public static function getSupportedViews(): Dynamic;

	public static function requestNavigateTo(view: Dynamic, ?opt_params: Dynamic, ?opt_ownerId: String): Void;
}
