/**
  Views : generated by hxtern
*/
package gadgets;
@:native("gadgets.views")
extern class Views{
	public static function getCurrentView(): gadgets.views.View {}

	public static function getParams(): Dynamic {}

	public static function getSupportedViews(): Dynamic {}

	public static function requestNavigateTo(view: hxtern.Any.Any2<gadgets.views.View,String>, ?opt_params: Dynamic, ?opt_ownerId: String): Void {}
}
