/**
DirectionsService : generated by hxtern
*/
package google.maps;

class DirectionsService{
	public function new();

	public function route(request: Dynamic, _callback: google.maps.DirectionsResult->google.maps.DirectionsStatus->Void): ;
}
