/**
FusionTablesPolygonOptions : generated by hxtern
*/
package google.maps;

extern class FusionTablesPolygonOptions {
	public function new() {}

	public var fillColor: String;

	public var fillOpacity: Float;

	public var strokeColor: String;

	public var strokeOpacity: Float;

	public var strokeWeight: Float;
}
