/**
  Places : generated by hxtern
*/
package google.maps;
@:native("google.maps.places")
extern class Places {
	public static var PlacesServiceStatus: Dynamic;

	public static var RankBy: Dynamic;
}
