/**
  PolygonOptions : generated by hxtern
*/
package google.maps;

class PolygonOptions{
	public function new();

	public var clickable: Bool;

	public var draggable: Bool;

	public var editable: Bool;

	public var fillColor: String;

	public var fillOpacity: Float;

	public var geodesic: Bool;

	public var map: google.maps.Map;

	public var paths: Dynamic;

	public var strokeColor: String;

	public var strokeOpacity: Float;

	public var strokePosition: google.maps.StrokePosition;

	public var strokeWeight: Float;

	public var visible: Bool;

	public var zIndex: Float;
}
