/**
  SymbolPath : generated by hxtern
*/
package google.maps;

extern class SymbolPath {
	public static var BACKWARD_CLOSED_ARROW: Dynamic;

	public static var BACKWARD_OPEN_ARROW: Dynamic;

	public static var CIRCLE: Dynamic;

	public static var FORWARD_CLOSED_ARROW: Dynamic;

	public static var FORWARD_OPEN_ARROW: Dynamic;
}
