/**
  TransitVehicle : generated by hxtern
*/
package google.maps;

extern class TransitVehicle {
	public function new() {}

	public var icon: String;

	public var local_icon: String;

	public var name: String;

	public var type: String;
}
