/**
  TransitDetails : generated by hxtern
*/
package google.maps;

extern class TransitDetails {
	public function new() {}

	public var arrival_stop: google.maps.TransitStop;

	public var arrival_time: google.maps.Time;

	public var departure_stop: google.maps.TransitStop;

	public var departure_time: google.maps.Time;

	public var headsign: String;

	public var headway: Float;

	public var line: google.maps.TransitLine;

	public var num_stops: Float;
}
