/**
OverlayCompleteEvent : generated by hxtern
*/
package google.maps.drawing;

extern class OverlayCompleteEvent {
	public function new() {}

	public var overlay: Hxtern.Any5<google.maps.Marker,google.maps.Polygon,google.maps.Polyline,google.maps.Rectangle,google.maps.Circle>;

	public var type: google.maps.drawing.OverlayType;
}
