/**
  Ime : generated by hxtern
*/
package chrome.input;
@:native("chrome.input.ime")
class Ime{
	public static function clearComposition(parameters: Dynamic<Float>, _callback: Bool->Void): Void;

	public static function commitText(parameters: Dynamic<Dynamic>, ?opt_callback: Bool->Void): Void;

	public static function keyEventHandled(requestId: String, response: Bool): Void;

	public static var onActivate: ChromeEvent;

	public static var onBlur: ChromeEvent;

	public static var onCandidateClicked: ChromeEvent;

	public static var onDeactivated: ChromeEvent;

	public static var onFocus: ChromeEvent;

	public static var onInputContextUpdate: ChromeEvent;

	public static var onKeyEvent: ChromeInputImeOnKeyEventEvent;

	public static var onMenuItemActivated: ChromeEvent;

	public static function setCandidates(parameters: Dynamic<Dynamic>, ?opt_callback: Bool->Void): Void;

	public static function setCandidateWindowProperties(parameters: Dynamic<Dynamic>, ?opt_callback: Bool->Void): Void;

	public static function setComposition(parameters: Dynamic<Dynamic>, ?opt_callback: Bool->Void): Void;

	public static function setCursorPosition(parameters: Dynamic<Float>, ?opt_callback: Bool->Void): Void;

	public static function setMenuItems(parameters: Dynamic<Dynamic>, ?opt_callback: Void->Void): Void;

	public static function updateMenuItems(parameters: Dynamic<Dynamic>, ?opt_callback: Void->Void): Void;
}
