/**
  Ime : generated by hxtern
*/
package chrome.input;
@:native("chrome.input.ime")
extern class Ime {
	public static function clearComposition(parameters: Dynamic<Float>, _callback: Bool->Void): Void {}

	public static function commitText(parameters: Dynamic<Hxtern.Any2<String,Float>>, ?opt_callback: Bool->Void): Void {}

	public static function keyEventHandled(requestId: String, response: Bool): Void {}

	public static var onActivate: ChromeEvent;

	public static var onBlur: ChromeEvent;

	public static var onCandidateClicked: ChromeEvent;

	public static var onDeactivated: ChromeEvent;

	public static var onFocus: ChromeEvent;

	public static var onInputContextUpdate: ChromeEvent;

	public static var onKeyEvent: ChromeInputImeOnKeyEventEvent;

	public static var onMenuItemActivated: ChromeEvent;

	public static function setCandidates(parameters: Dynamic<Hxtern.Any2<Float,Dynamic<Hxtern.Any2<String,Float>>>>, ?opt_callback: Bool->Void): Void {}

	public static function setCandidateWindowProperties(parameters: Dynamic<Hxtern.Any2<Float,Dynamic<Hxtern.Any3<String,Float,Bool>>>>, ?opt_callback: Bool->Void): Void {}

	public static function setComposition(parameters: Dynamic<Hxtern.Any3<String,Float,Dynamic<Hxtern.Any2<String,Float>>>>, ?opt_callback: Bool->Void): Void {}

	public static function setCursorPosition(parameters: Dynamic<Float>, ?opt_callback: Bool->Void): Void {}

	public static function setMenuItems(parameters: Dynamic<Hxtern.Any2<String,Array<Dynamic<Hxtern.Any2<String,Bool>>>>>, ?opt_callback: Void->Void): Void {}

	public static function updateMenuItems(parameters: Dynamic<Hxtern.Any2<String,Array<Dynamic<Hxtern.Any2<String,Bool>>>>>, ?opt_callback: Void->Void): Void {}
}
