/**
  PanoramioFeature : generated by hxtern
*/
package google.maps.panoramio;

extern class PanoramioFeature {
	public function new() {}

	public var author: String;

	public var photoId: String;

	public var title: String;

	public var url: String;

	public var userId: String;
}
