/**
SpeechRecognitionError : generated by hxtern
*/
package ;

extern class SpeechRecognitionError extends Event {
	public function new() {}

	public var error: String;

	public var message: String;
}
