/**
SpeechRecognitionEvent : generated by hxtern
*/
package ;
class SpeechRecognitionEvent{
	public function new();

	public var emma: Document;

	public var interpretation: Dynamic;

	public var resultIndex: Float;

	public var results: SpeechRecognitionResultList;
}