/**
SpeechRecognitionResult : generated by hxtern
*/
package ;
class SpeechRecognitionResult{
	public function new();

	public var isFinal: Bool;

	public function item(): Void;

	public var length: Float;
}