/**
SpeechGrammarList : generated by hxtern
*/
package ;

class SpeechGrammarList{
	public function new();

	public function addFromString(): Void {}

	public function addFromUri(): Void {}

	public function item(): Void {}

	public var length: Float;
}
