/**
webkitSpeechRecognitionError : generated by hxtern
*/
package ;
@:native("webkitSpeechRecognitionError")
extern class WebkitSpeechRecognitionError extends SpeechRecognitionError {
	public function new() {}

	public var error: String;

	public var message: String;
}
