/**
webkitSpeechRecognitionError : generated by hxtern
*/
package ;
@:native("webkitSpeechRecognitionError")
extern class WebkitSpeechRecognitionError{
	public function new();

	public var error: String;

	public var message: String;
}
