/**
MVCObject : generated by hxtern
*/
package google.maps;

class MVCObject{
	public function new();

	public function bindTo(key: String, target: google.maps.MVCObject, ?opt_targetKey: String, ?opt_noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setValues(values: Dynamic): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
