/**
  ButtonClickedEvent : generated by hxtern
*/
package chrome.notifications;

class ButtonClickedEvent{
	public function new();

	public function addListener(_callback: chrome.notifications.ButtonCallback): Void;
}
