/**
  ClickedEvent : generated by hxtern
*/
package chrome.notifications;

extern class ClickedEvent{
	public function new();

	public function addListener(_callback: chrome.notifications.StringCallback): Void {}
}
