/**
  ClosedEvent : generated by hxtern
*/
package chrome.notifications;
class ClosedEvent{
	public function new();

	public function addListener(_callback: chrome.notifications.ClosedCallback): Void;
}