/**
  NotificationOptions : generated by hxtern
*/
package chrome.notifications;

extern typedef NotificationOptions = {type: Hxtern.Any2<String,Null<Dynamic>>, iconUrl: Hxtern.Any2<String,Null<Dynamic>>, title: Hxtern.Any2<String,Null<Dynamic>>, message: Hxtern.Any2<String,Null<Dynamic>>, contextMessage: Hxtern.Any2<String,Null<Dynamic>>, priority: Hxtern.Any2<Float,Null<Dynamic>>, eventTime: Hxtern.Any2<Float,Null<Dynamic>>, buttons: Hxtern.Any2<Array<chrome.notifications.NotificationButton>,Null<Dynamic>>, imageUrl: Hxtern.Any2<String,Null<Dynamic>>, items: Hxtern.Any2<Array<chrome.notifications.NotificationItem>,Null<Dynamic>>, progress: Hxtern.Any2<Float,Null<Dynamic>>, isClickable: Hxtern.Any2<Bool,Null<Dynamic>>}

