/**
  Gadgets : generated by hxtern
*/
package ;
@:native("gadgets")
extern class Gadgets {
	public static var config: Dynamic;

	public static var flash: Dynamic;

	public static var io: Dynamic;

	public static var json: Dynamic;

	public static var rpc: Dynamic;

	public static var util: Dynamic;

	public static var views: Dynamic;

	public static var window: Dynamic;
}
