/**
DirectionsRendererOptions : generated by hxtern
*/
package google.maps;

class DirectionsRendererOptions{
	public function new();

	public var directions: google.maps.DirectionsResult;

	public var draggable: Bool;

	public var hideRouteList: Bool;

	public var infoWindow: google.maps.InfoWindow;

	public var map: google.maps.Map;

	public var markerOptions: google.maps.MarkerOptions;

	public var panel: Node;

	public var polylineOptions: google.maps.PolylineOptions;

	public var preserveViewport: Bool;

	public var routeIndex: Float;

	public var suppressBicyclingLayer: Bool;

	public var suppressInfoWindows: Bool;

	public var suppressMarkers: Bool;

	public var suppressPolylines: Bool;
}
