/**
DirectionsStep : generated by hxtern
*/
package google.maps;

class DirectionsStep{
	public function new();

	public var distance: google.maps.Distance;

	public var duration: google.maps.Duration;

	public var end_location: google.maps.LatLng;

	public var instructions: String;

	public var path: Array<google.maps.LatLng>;

	public var start_location: google.maps.LatLng;

	public var travel_mode: google.maps.TravelMode;
}
