/**
FusionTablesStyle : generated by hxtern
*/
package google.maps;

class FusionTablesStyle{
	public function new();

	public var markerOptions: hxtern.Any.Any2<google.maps.FusionTablesMarkerOptions,Dynamic<Dynamic>>;

	public var polygonOptions: hxtern.Any.Any2<google.maps.FusionTablesPolygonOptions,Dynamic<Dynamic>>;

	public var polylineOptions: hxtern.Any.Any2<google.maps.FusionTablesPolylineOptions,Dynamic<Dynamic>>;

	public var where: String;
}
