/**
Polygon : generated by hxtern
*/
package google.maps;

class Polygon{
	public function new(?opt_opts: hxtern.Any2<google.maps.PolygonOptions,Dynamic<Dynamic>>);

	public function bindTo(key: String, target: google.maps.MVCObject, ?opt_targetKey: String, ?opt_noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function getEditable(): Bool;

	public function getMap(): google.maps.Map;

	public function getPath(): google.maps.MVCArray<google.maps.LatLng>;

	public function getPaths(): google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setEditable(editable: Bool): ;

	public function setMap(map: google.maps.Map): ;

	public function setOptions(options: hxtern.Any2<google.maps.PolygonOptions,Dynamic<Dynamic>>): ;

	public function setPath(path: hxtern.Any2<google.maps.MVCArray<google.maps.LatLng>,Array<google.maps.LatLng>>): ;

	public function setPaths(paths: hxtern.Any4<google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>,google.maps.MVCArray<google.maps.LatLng>,Array<Array<google.maps.LatLng>>,Array<google.maps.LatLng>>): ;

	public function setValues(values: hxtern.Any2<Dynamic,>): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
