/**
PolygonOptions : generated by hxtern
*/
package google.maps;

class PolygonOptions{
	public function new();

	public var clickable: Bool;

	public var fillColor: String;

	public var fillOpacity: Float;

	public var geodesic: Bool;

	public var map: google.maps.Map;

	public var paths: google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>;

	public var strokeColor: String;

	public var strokeOpacity: Float;

	public var strokeWeight: Float;

	public var zIndex: Float;
}
