/**
PolylineOptions : generated by hxtern
*/
package google.maps;

class PolylineOptions{
	public function new();

	public var clickable: Bool;

	public var geodesic: Bool;

	public var map: google.maps.Map;

	public var path: hxtern.Any.Any2<google.maps.MVCArray<google.maps.LatLng>,Array<google.maps.LatLng>>;

	public var strokeColor: String;

	public var strokeOpacity: Float;

	public var strokeWeight: Float;

	public var zIndex: Float;
}
