/**
  ClientLocation : generated by hxtern
*/
package google.loader;

class ClientLocation{
	public static var address: Dynamic;

	public static var latitude: Float;

	public static var longitude: Float;
}
