/**
  Global : generated by hxtern
*/
package fileapi.synchronous;

extern class Global {
	public static function requestFileSystemSync(type: Float, size: Float): FileSystemSync {}

	public static function webkitRequestFileSystemSync(type: Float, size: Float): FileSystemSync {}
}
