/**
  DrawingManagerOptions : generated by hxtern
*/
package google.maps.drawing;

class DrawingManagerOptions{
	public function new();

	public var circleOptions: Dynamic;

	public var drawingControl: Bool;

	public var drawingControlOptions: Dynamic;

	public var drawingMode: google.maps.drawing.OverlayType;

	public var map: google.maps.Map;

	public var markerOptions: Dynamic;

	public var polygonOptions: Dynamic;

	public var polylineOptions: Dynamic;

	public var rectangleOptions: Dynamic;
}
