/**
OverlayCompleteEvent : generated by hxtern
*/
package google.maps.drawing;

class OverlayCompleteEvent{
	public function new();

	public var overlay: Dynamic;

	public var type: google.maps.drawing.OverlayType;
}
