/**
StorageUnitInfo : generated by hxtern
*/
package chrome.system.storage;

extern class StorageUnitInfo {
	public function new() {}

	public static var capacity: Float;

	public static var id: String;

	public static var name: String;

	public static var type: String;
}
