/**
  DynamicMapsEngineMouseEvent : generated by hxtern
*/
package google.maps.visualization;

extern class DynamicMapsEngineMouseEvent {
	public function new() {}

	public var featureId: String;

	public function getDetails(_callback: google.maps.visualization.MapsEngineMouseEvent->Void): Null<Dynamic> {}

	public var latLng: google.maps.LatLng;
}
