/**
SourceBuffer : generated by hxtern
*/
package ;

class SourceBuffer{
	public function new();

	public function abort(): Void;

	public function addEventListener(): Void;

	public function append(data: Uint8Array): Void;

	public function appendBuffer(data: Dynamic): Void;

	public var appendMode: String;

	public var appendWindowEnd: Float;

	public var appendWindowStart: Float;

	public var buffered: TimeRanges;

	public function dispatchEvent(): Void;

	public function remove(start: Float, end: Float): Void;

	public function removeEventListener(): Void;

	public var timestampOffset: Float;

	public var updating: Bool;
}
