/**
  AlarmCreateInfo : generated by hxtern
*/
package chrome.alarms;

extern typedef AlarmCreateInfo = {when: Hxtern.Any2<Float,Null<Dynamic>>, delayInMinutes: Hxtern.Any2<Float,Null<Dynamic>>, periodInMinutes: Hxtern.Any2<Float,Null<Dynamic>>}

