/**
PlaceSearchPagination : generated by hxtern
*/
package google.maps.places;

extern class PlaceSearchPagination {
	public function new() {}

	public var hasNextPage: Bool;

	public function nextPage(): Null<Dynamic> {}
}
