/**
PlaceSearchPagination : generated by hxtern
*/
package google.maps.places;

class PlaceSearchPagination{
	public function new();

	public var hasNextPage: Bool;

	public function nextPage(): Null<Dynamic> {}
}
