/**
  ControlPosition : generated by hxtern
*/
package google.maps;

class ControlPosition{
	public static var BOTTOM_CENTER: Dynamic;

	public static var BOTTOM_LEFT: Dynamic;

	public static var BOTTOM_RIGHT: Dynamic;

	public static var LEFT_BOTTOM: Dynamic;

	public static var LEFT_CENTER: Dynamic;

	public static var LEFT_TOP: Dynamic;

	public static var RIGHT_BOTTOM: Dynamic;

	public static var RIGHT_CENTER: Dynamic;

	public static var RIGHT_TOP: Dynamic;

	public static var TOP_CENTER: Dynamic;

	public static var TOP_LEFT: Dynamic;

	public static var TOP_RIGHT: Dynamic;
}
