/**
  DistanceMatrixElementStatus : generated by hxtern
*/
package google.maps;

extern class DistanceMatrixElementStatus {
	public static var NOT_FOUND: Dynamic;

	public static var OK: Dynamic;

	public static var ZERO_RESULTS: Dynamic;
}
