/**
FusionTablesStyle : generated by hxtern
*/
package google.maps;

class FusionTablesStyle{
	public function new();

	public var markerOptions: google.maps.FusionTablesMarkerOptions;

	public var polygonOptions: google.maps.FusionTablesPolygonOptions;

	public var polylineOptions: google.maps.FusionTablesPolylineOptions;

	public var where: String;
}
