/**
  MapTypeControlOptions : generated by hxtern
*/
package google.maps;

class MapTypeControlOptions{
	public function new();

	public var mapTypeIds: Dynamic;

	public var position: google.maps.ControlPosition;

	public var style: google.maps.MapTypeControlStyle;
}
