/**
  TravelMode : generated by hxtern
*/
package google.maps;

extern class TravelMode {
	public static var BICYCLING: Dynamic;

	public static var DRIVING: Dynamic;

	public static var TRANSIT: Dynamic;

	public static var WALKING: Dynamic;
}
