/**
  Navigator : generated by hxtern
*/
package ;
@:native("navigator")
class Navigator{
	public static function getGamepads(): Array<Gamepad>;

	public static function webkitGetGamepads(): Array<Gamepad>;
}