/**
  WeatherForecast : generated by hxtern
*/
package google.maps.weather;

extern class WeatherForecast {
	public function new() {}

	public var day: String;

	public var description: String;

	public var high: Float;

	public var low: Float;

	public var shortDay: String;
}
