/**
AcceptInfo : generated by hxtern
*/
package chrome.socket;

extern class AcceptInfo {
	public function new() {}

	public var resultCode: Float;

	public var socketId: Hxtern.Any2<Float,Null<Dynamic>>;
}
