/**
RecvFromInfo : generated by hxtern
*/
package chrome.socket;

extern class RecvFromInfo{
	public function new();

	public var address: String;

	public var data: ArrayBuffer;

	public var port: Float;

	public var resultCode: Float;
}
