/**
SocketInfo : generated by hxtern
*/
package chrome.socket;

extern class SocketInfo{
	public function new();

	public var connected: Bool;

	public var localAddress: Hxtern.Any2<String,Null<Dynamic>>;

	public var localPort: Hxtern.Any2<Float,Null<Dynamic>>;

	public var peerAddress: Hxtern.Any2<String,Null<Dynamic>>;

	public var peerPort: Hxtern.Any2<Float,Null<Dynamic>>;

	public var socketType: String;
}
