/**
SocketInfo : generated by hxtern
*/
package chrome.socket;

class SocketInfo{
	public function new();

	public var connected: Bool;

	public var localAddress: String;

	public var localPort: Float;

	public var peerAddress: String;

	public var peerPort: Float;

	public var socketType: String;
}
