/**
SocketInfo : generated by hxtern
*/
package chrome.socket;

class SocketInfo{
	public function new();

	public var connected: Bool;

	public var localAddress: Dynamic;

	public var localPort: Dynamic;

	public var peerAddress: Dynamic;

	public var peerPort: Dynamic;

	public var socketType: String;
}
