/**
ElevationResult : generated by hxtern
*/
package google.maps;

class ElevationResult{
	public function new();

	public var elevation: Float;

	public var location: google.maps.LatLng;

	public var resolution: Float;
}
