/**
FusionTablesPolylineOptions : generated by hxtern
*/
package google.maps;

extern class FusionTablesPolylineOptions {
	public function new() {}

	public var strokeColor: String;

	public var strokeOpacity: Float;

	public var strokeWeight: Float;
}
