/**
Map : generated by hxtern
*/
package google.maps;

class Map{
	public function new(mapDiv: Node, ?opt_opts: google.maps.MapOptions);

	public function addListener(eventName: String, handler: Dynamic): google.maps.MapsEventListener;

	public function bindTo(key: String, target: google.maps.MVCObject, ?opt_targetKey: String, ?opt_noNotify: Bool): ;

	public function changed(key: String): ;

	public var controls: Array<google.maps.MVCArray<Node>>;

	public function fitBounds(bounds: google.maps.LatLngBounds): ;

	public function get(key: String): Dynamic;

	public function getBounds(): google.maps.LatLngBounds;

	public function getCenter(): google.maps.LatLng;

	public function getDiv(): Node;

	public function getHeading(): Float;

	public function getMapTypeId(): google.maps.MapTypeId;

	public function getProjection(): google.maps.Projection;

	public function getStreetView(): google.maps.StreetViewPanorama;

	public function getTilt(): Float;

	public function getZoom(): Float;

	public var mapTypes: google.maps.MapTypeRegistry;

	public function notify(key: String): ;

	public var overlayMapTypes: google.maps.MVCArray<google.maps.MapType>;

	public function panBy(x: Float, y: Float): ;

	public function panTo(latLng: google.maps.LatLng): ;

	public function panToBounds(latLngBounds: google.maps.LatLngBounds): ;

	public function set(key: String, value: Dynamic): ;

	public function setCenter(latlng: google.maps.LatLng): ;

	public function setHeading(heading: Float): ;

	public function setMapTypeId(mapTypeId: google.maps.MapTypeId): ;

	public function setOptions(options: google.maps.MapOptions): ;

	public function setStreetView(panorama: google.maps.StreetViewPanorama): ;

	public function setTilt(tilt: Float): ;

	public function setValues(values: Dynamic): ;

	public function setZoom(zoom: Float): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
