/**
MapTypeStyle : generated by hxtern
*/
package google.maps;

class MapTypeStyle{
	public function new();

	public var elementType: String;

	public var featureType: String;

	public var stylers: Array<google.maps.MapTypeStyler>;
}
