/**
MapTypeControlOptions : generated by hxtern
*/
package google.maps;

extern class MapTypeControlOptions {
	public function new() {}

	public var mapTypeIds: Hxtern.Any2<Array<google.maps.MapTypeId>,Array<String>>;

	public var position: google.maps.ControlPosition;

	public var style: google.maps.MapTypeControlStyle;
}
