/**
MarkerOptions : generated by hxtern
*/
package google.maps;

class MarkerOptions{
	public function new();

	public var anchorPoint: google.maps.Point;

	public var animation: google.maps.Animation;

	public var clickable: Bool;

	public var cursor: String;

	public var draggable: Bool;

	public var flat: Bool;

	public var icon: hxtern.Any.Any3<String,google.maps.Icon,google.maps.Symbol>;

	public var map: hxtern.Any.Any2<google.maps.Map,google.maps.StreetViewPanorama>;

	public var optimized: Bool;

	public var position: google.maps.LatLng;

	public var raiseOnDrag: Bool;

	public var shadow: hxtern.Any.Any3<String,google.maps.Icon,google.maps.Symbol>;

	public var shape: google.maps.MarkerShape;

	public var title: String;

	public var visible: Bool;

	public var zIndex: Float;
}
