/**
PolygonOptions : generated by hxtern
*/
package google.maps;

class PolygonOptions{
	public function new();

	public var clickable: Bool;

	public var editable: Bool;

	public var fillColor: String;

	public var fillOpacity: Float;

	public var geodesic: Bool;

	public var map: google.maps.Map;

	public var paths: hxtern.Any4<google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>,google.maps.MVCArray<google.maps.LatLng>,Array<Array<google.maps.LatLng>>,Array<google.maps.LatLng>>;

	public var strokeColor: String;

	public var strokeOpacity: Float;

	public var strokePosition: google.maps.StrokePosition;

	public var strokeWeight: Float;

	public var visible: Bool;

	public var zIndex: Float;
}
