/**
  ZoomControlStyle : generated by hxtern
*/
package google.maps;

class ZoomControlStyle{
	public static var DEFAULT: Dynamic;

	public static var LARGE: Dynamic;

	public static var SMALL: Dynamic;
}
