/**
DirectionsLeg : generated by hxtern
*/
package google.maps;

class DirectionsLeg{
	public function new();

	public var distance: google.maps.DirectionsDistance;

	public var duration: google.maps.DirectionsDuration;

	public var end_address: String;

	public var end_location: google.maps.LatLng;

	public var start_address: String;

	public var start_location: google.maps.LatLng;

	public var steps: Array<google.maps.DirectionsStep>;
}
