/**
DirectionsWaypoint : generated by hxtern
*/
package google.maps;

class DirectionsWaypoint{
	public function new();

	public var location: hxtern.Any2<google.maps.LatLng,String>;

	public var stopover: Bool;
}
