/**
DirectionsRenderer : generated by hxtern
*/
package google.maps;

class DirectionsRenderer{
	public function new(?opt_opts: Dynamic<Dynamic>);

	public function bindTo(key: String, target: google.maps.MVCObject, ?targetKey: String, ?noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function getDirections(): hxtern.Any2<google.maps.DirectionsResult,Dynamic<Dynamic>>;

	public function getMap(): google.maps.Map;

	public function getPanel(): Node;

	public function getRouteIndex(): Float;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setDirections(directions: hxtern.Any2<google.maps.DirectionsResult,Dynamic<Dynamic>>): ;

	public function setMap(map: google.maps.Map): ;

	public function setOptions(options: Dynamic<Dynamic>): ;

	public function setPanel(panel: Node): ;

	public function setRouteIndex(routeIndex: Float): ;

	public function setValues(values: hxtern.Any2<Dynamic,>): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
