/**
ElevationService : generated by hxtern
*/
package google.maps;

class ElevationService{
	public function new();

	public function getElevationAlongPath(request: Dynamic, _callback: Array<Dynamic>->google.maps.ElevationStatus->Void): ;

	public function getElevationForLocations(request: Dynamic, _callback: Array<Dynamic>->google.maps.ElevationStatus->Void): ;
}
