/**
  Encoding : generated by hxtern
*/
package google.maps;
@:native("google.maps.encoding")
class Encoding{
	public static function decodePath(encodedPath: String): Array<google.maps.LatLng>;

	public static function encodePath(path: hxtern.Any.Any2<Array<google.maps.LatLng>,google.maps.MVCArray<google.maps.LatLng>>): String;
}
