/**
FusionTablesLayer : generated by hxtern
*/
package google.maps;

class FusionTablesLayer{
	public function new(tableId: String, ?opt_opts: Dynamic<Dynamic>);

	public function bindTo(key: String, target: google.maps.MVCObject, ?targetKey: String, ?noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function getMap(): google.maps.Map;

	public function getQuery(): String;

	public function getTableId(): Float;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setMap(map: google.maps.Map): ;

	public function setOptions(options: Dynamic<Dynamic>): ;

	public function setQuery(query: String): ;

	public function setTableId(tableId: Float): ;

	public function setValues(values: Dynamic): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
