/**
GeocoderAddressComponent : generated by hxtern
*/
package google.maps;

extern class GeocoderAddressComponent {
	public function new() {}

	public var long_name: String;

	public var short_name: String;

	public var types: Array<String>;
}
