/**
Geocoder : generated by hxtern
*/
package google.maps;

class Geocoder{
	public function new();

	public function geocode(request: Dynamic, _callback: Array<Dynamic>->google.maps.GeocoderStatus->Void): ;
}
