/**
Geocoder : generated by hxtern
*/
package google.maps;

extern class Geocoder{
	public function new();

	public function geocode(request: Hxtern.Any2<google.maps.GeocoderRequest,Dynamic<Dynamic>>, _callback: Array<Hxtern.Any2<google.maps.GeocoderResult,Dynamic<Dynamic>>>->google.maps.GeocoderStatus->Void): Null<Dynamic> {}
}
