/**
MapOptions : generated by hxtern
*/
package google.maps;

class MapOptions{
	public function new();

	public var backgroundColor: String;

	public var center: google.maps.LatLng;

	public var disableDefaultUI: Bool;

	public var disableDoubleClickZoom: Bool;

	public var draggable: Bool;

	public var draggableCursor: String;

	public var draggingCursor: String;

	public var keyboardShortcuts: Bool;

	public var mapTypeControl: Bool;

	public var mapTypeControlOptions: Dynamic<Dynamic>;

	public var mapTypeId: google.maps.MapTypeId;

	public var maxZoom: Float;

	public var minZoom: Float;

	public var noClear: Bool;

	public var panControl: Bool;

	public var panControlOptions: Dynamic<Dynamic>;

	public var scaleControl: Bool;

	public var scaleControlOptions: Dynamic<Dynamic>;

	public var scrollwheel: Bool;

	public var streetView: google.maps.StreetViewPanorama;

	public var streetViewControl: Bool;

	public var streetViewControlOptions: Dynamic<Dynamic>;

	public var zoom: Float;

	public var zoomControl: Bool;

	public var zoomControlOptions: Dynamic<Dynamic>;
}
