/**
Marker : generated by hxtern
*/
package google.maps;

class Marker{
	public function new(?opt_opts: Dynamic<Dynamic>);

	public function bindTo(key: String, target: google.maps.MVCObject, ?targetKey: String, ?noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function getAnimation(): google.maps.Animation;

	public function getClickable(): Bool;

	public function getCursor(): String;

	public function getDraggable(): Bool;

	public function getFlat(): Bool;

	public function getIcon(): Dynamic;

	public function getMap(): Dynamic;

	public function getPosition(): google.maps.LatLng;

	public function getShadow(): Dynamic;

	public function getShape(): google.maps.MarkerShape;

	public function getTitle(): String;

	public function getVisible(): Bool;

	public function getZIndex(): Float;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setAnimation(animation: google.maps.Animation): ;

	public function setClickable(flag: Bool): ;

	public function setCursor(cursor: String): ;

	public function setDraggable(flag: Bool): ;

	public function setFlat(flag: Bool): ;

	public function setIcon(icon: Dynamic): ;

	public function setMap(map: Dynamic): ;

	public function setOptions(options: Dynamic<Dynamic>): ;

	public function setPosition(latlng: google.maps.LatLng): ;

	public function setShadow(shadow: Dynamic): ;

	public function setShape(shape: google.maps.MarkerShape): ;

	public function setTitle(title: String): ;

	public function setValues(values: Dynamic): ;

	public function setVisible(visible: Bool): ;

	public function setZIndex(zIndex: Float): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
