/**
MarkerImage : generated by hxtern
*/
package google.maps;

extern class MarkerImage{
	public function new(url: String, ?size: google.maps.Size, ?origin: google.maps.Point, ?anchor: google.maps.Point, ?scaledSize: google.maps.Size);

	public var size: google.maps.Size;
}
