/**
MaxZoomService : generated by hxtern
*/
package google.maps;

class MaxZoomService{
	public function new();

	public function getMaxZoomAtLatLng(latlng: google.maps.LatLng, _callback: Dynamic->Void): ;
}
