/**
  Spherical : generated by hxtern
*/
package google.maps;
@:native("google.maps.spherical")
class Spherical{
	public static function computeArea(loop: Array<google.maps.LatLng>, ?radius: Float): Float;

	public static function computeDistanceBetween(from: google.maps.LatLng, to: google.maps.LatLng, ?radius: Float): Float;

	public static function computeHeading(from: google.maps.LatLng, to: google.maps.LatLng): Float;

	public static function computeLength(path: Array<google.maps.LatLng>, ?radius: Float): Float;

	public static function computeOffset(from: google.maps.LatLng, distance: Float, heading: Float, ?radius: Float): google.maps.LatLng;

	public static function interpolate(from: google.maps.LatLng, to: google.maps.LatLng, fraction: Float): google.maps.LatLng;
}
