/**
  PanoramioMouseEvent : generated by hxtern
*/
package google.maps.panoramio;

extern class PanoramioMouseEvent {
	public function new() {}

	public var featureDetails: google.maps.panoramio.PanoramioFeature;

	public var infoWindowHtml: String;

	public var latLng: google.maps.LatLng;

	public var pixelOffset: google.maps.Size;
}
