/**
  Address : generated by hxtern
*/

@:native("google.loader.ClientLocation.address")
class Address{
	public static var city: String;

	public static var country: String;

	public static var country_code: String;

	public static var region: String;
}
