/**
Popup : generated by hxtern
An OAuth popup for granting one time access to user data.
*/
package gadgets.oauth;

class Popup{
	public function new(destination: String, windowOptions: String, openCallback: Dynamic, closeCallback: Dynamic);

	public function createApprovedOnClick(): Dynamic;

	public function createOpenerOnClick(): Dynamic;
}