/**
PlacesService : generated by hxtern
*/
package google.maps.places;

class PlacesService{
	public function new(attrContainer: Dynamic);

	public function getDetails(request: Dynamic, _callback: google.maps.places.PlaceResult->google.maps.places.PlacesServiceStatus->Void): ;

	public function search(request: Dynamic, _callback: Array<google.maps.places.PlaceResult>->google.maps.places.PlacesServiceStatus->Void): ;
}
