/**
AudioProcessingEvent : generated by hxtern
*/
package ;

class AudioProcessingEvent{
	public function new();

	public var inputBuffer: AudioBuffer;

	public var node: ScriptProcessorNode;

	public var outputBuffer: AudioBuffer;

	public var playbackTime: Float;
}