/**
BiquadFilterNode : generated by hxtern
*/
package ;

extern class BiquadFilterNode extends AudioNode {
	public function new() {}

	public var channelCount: Float;

	public var channelCountMode: String;

	public var channelInterpretation: String;

	public function connect(destination: AudioNode, ?output: Float, ?input: Float): Void {}

	public var context: AudioContext;

	public var detune: AudioParam;

	public function disconnect(?output: Float): Void {}

	public var frequency: AudioParam;

	public var gain: AudioParam;

	public function getFrequencyResponse(frequencyHz: Float32Array, magResponse: Float32Array, phaseResponse: Float32Array): Void {}

	public var numberOfInputs: Float;

	public var numberOfOutputs: Float;

	public var Q: AudioParam;

	public var type: Float;
}
