/**
OscillatorNode : generated by hxtern
*/
package ;

class OscillatorNode{
	public function new();

	public var channelCount: Float;

	public var channelCountMode: String;

	public var channelInterpretation: String;

	public function connect(destination: AudioNode, ?output: Float, ?input: Float): Void;

	public var context: AudioContext;

	public var detune: AudioParam;

	public function disconnect(?output: Float): Void;

	public var frequency: AudioParam;

	public var numberOfInputs: Float;

	public var numberOfOutputs: Float;

	public var onended: EventListener;

	/**
	  To be deprecated.
	 */
	public var playbackState: Float;

	public var setPeriodicWave: PeriodicWave->Void;

	/**
	  To be deprecated.
	 */
	public var setWaveTable: WaveTable->Void;

	public var start: Float->Void;

	public var stop: Float->Void;

	public var type: String;
}