/**
event : generated by hxtern
*/
package jQuery;
@:native("jQuery.event")
class Event{
	public function new(eventType: String);

	public var currentTarget: Element;

	public var data: Dynamic;

	public function isDefaultPrevented(): Bool;

	public function isImmediatePropagationStopped(): Bool;

	public function isPropagationStopped(): Bool;

	public var namespace: String;

	public var pageX: Float;

	public var pageY: Float;

	public function preventDefault(): ;

	public var relatedTarget: Element;

	public var result: Dynamic;

	public function stopImmediatePropagation(): ;

	public function stopPropagation(): ;

	public var target: Element;

	public var timeStamp: Float;

	public var type: String;

	public var which: String;
}
