/**
FusionTablesStyle : generated by hxtern
*/
package google.maps;

class FusionTablesStyle{
	public function new();

	public var markerOptions: Dynamic;

	public var polygonOptions: Dynamic;

	public var polylineOptions: Dynamic;

	public var where: String;
}
