/**
GeocoderResult : generated by hxtern
*/
package google.maps;

class GeocoderResult{
	public function new();

	public var address_components: Array<google.maps.GeocoderAddressComponent>;

	public var formatted_address: String;

	public var geometry: google.maps.GeocoderGeometry;

	public var postcode_localities: Array<String>;

	public var types: Array<String>;
}
