/**
  IconSequence : generated by hxtern
*/
package google.maps;

extern class IconSequence {
	public function new() {}

	public var fixedRotation: Bool;

	public var icon: google.maps.Symbol;

	public var offset: String;

	public var repeat: String;
}
