/**
  PolylineOptions : generated by hxtern
*/
package google.maps;

extern class PolylineOptions {
	public function new() {}

	public var clickable: Bool;

	public var draggable: Bool;

	public var editable: Bool;

	public var geodesic: Bool;

	public var icons: Array<google.maps.IconSequence>;

	public var map: google.maps.Map;

	public var path: Hxtern.Any2<google.maps.MVCArray<google.maps.LatLng>,Array<google.maps.LatLng>>;

	public var strokeColor: String;

	public var strokeOpacity: Float;

	public var strokeWeight: Float;

	public var visible: Bool;

	public var zIndex: Float;
}
