/**
PolyMouseEvent : generated by hxtern
*/
package google.maps;

extern class PolyMouseEvent extends google.maps.MouseEvent {
	public function new() {}

	public var edge: Float;

	public var latLng: google.maps.LatLng;

	public var path: Float;

	public function stop(): Null<Dynamic> {}

	public var vertex: Float;
}
