/**
  StreetViewLocation : generated by hxtern
*/
package google.maps;

extern class StreetViewLocation {
	public function new() {}

	public var description: String;

	public var latLng: google.maps.LatLng;

	public var pano: String;
}
