/**
  Entry : generated by hxtern
*/
package google.feeds;

extern class Entry{
	public function new();

	public var categories: Array<String>;

	public var content: String;

	public var contentSnippet: String;

	public var link: String;

	public var mediaGroup: String;

	public var publishedDate: String;

	public var title: String;

	public var xmlNode: Node;
}
