/**
Feed : generated by hxtern
*/
package google.feeds;
class Feed{
	public function new(url: String);

	public function getElementsByTagNameNS(node: Node, ns: String, localName: String): NodeList;

	public function includeHistoricalEntries(): Void;

	public function load(_callback: google.feeds.LoadResult->Void): Void;

	public function setNumEntries(num: Float): Void;

	public function setResultFormat(format: String): Void;
}