/**
  FeedResult : generated by hxtern
*/
package google.feeds;

extern class FeedResult {
	public function new() {}

	public var author: String;

	public var description: String;

	public var entries: Array<google.feeds.Entry>;

	public var feedUrl: String;

	public var link: String;

	public var title: String;
}
