/**
  FindFeedResult : generated by hxtern
*/
package google.feeds;

extern class FindFeedResult{
	public function new() {}

	public var entries: Array<google.feeds.FindFeedResultEntry>;

	public var error: google.feeds.FeedError_;
}
