/**
  FindFeedResultEntry : generated by hxtern
*/
package google.feeds;

extern class FindFeedResultEntry{
	public function new();

	public var contentSnippet: String;

	public var link: String;

	public var title: String;

	public var url: String;
}
