/**
  LoadResult : generated by hxtern
*/
package google.feeds;
class LoadResult{
	public function new();

	public var error: google.feeds.FeedError_;

	public var feed: google.feeds.FeedResult;

	public var xmlDocument: Document;
}