/**
jQueryObject : generated by hxtern
*/
package ;
@:native("jQueryObject")
class JQueryObject{
	public function new();

	public function add(arg1: jQuerySelector, ?context: Element): jQueryObject;

	public function addClass(arg1: String): jQueryObject;

	public function after(arg1: String): jQueryObject;

	public function ajaxComplete(handler: jQuery.event->XMLHttpRequest->Dynamic<Dynamic>->Void): jQueryObject;

	public function ajaxError(handler: jQuery.event->XMLHttpRequest->Dynamic<Dynamic>->Dynamic->Void): jQueryObject;

	public function ajaxSend(handler: jQuery.event->XMLHttpRequest->Dynamic<Dynamic>->Void): jQueryObject;

	public function ajaxStart(handler: Void->Void): jQueryObject;

	public function ajaxStop(handler: Void->Void): jQueryObject;

	public function ajaxSuccess(handler: jQuery.event->XMLHttpRequest->Dynamic<Dynamic>->Void): jQueryObject;

	public function andSelf(): jQueryObject;

	public function animate(properties: Dynamic<Dynamic>, ?arg2: String, ?easing: String, ?_callback: Void->Void): jQueryObject;

	public function append(arg1: String): jQueryObject;

	public function appendTo(target: jQuerySelector): jQueryObject;

	public function attr(arg1: String, ?arg2: String): String;

	public function before(arg1: String): jQueryObject;

	public function bind(arg1: String, ?eventData: Dynamic, ?arg3: jQuery.event->Void): jQueryObject;

	public function blur(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function change(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function children(?selector: jQuerySelector): jQueryObject;

	public function clearQueue(?queueName: String): jQueryObject;

	public function click(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function clone(?withDataAndEvents: Bool): jQueryObject;

	public function closest(arg1: jQuerySelector, ?context: Element): jQueryObject;

	public function contents(): jQueryObject;

	public var context: Element;

	public function css(arg1: String, ?arg2: String): String;

	public function data(?arg1: String, ?value: Dynamic): jQueryObject;

	public function dblclick(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function delay(duration: Float, ?queueName: String): jQueryObject;

	public function delegate(selector: String, eventType: String, arg3: Void->Void, ?handler: Void->Void): jQueryObject;

	public function dequeue(?queueName: String): jQueryObject;

	public function detach(?selector: jQuerySelector): jQueryObject;

	public function die(?eventType: String, ?handler: String): jQueryObject;

	public function each(fnc: Float->Element->Void): jQueryObject;

	public function empty(): jQueryObject;

	public function end(): jQueryObject;

	public function eq(arg1: Float): jQueryObject;

	public function error(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function fadeIn(?duration: String, ?arg2: Void->Void, ?_callback: Void->Void): jQueryObject;

	public function fadeOut(?duration: String, ?arg2: Void->Void, ?_callback: Void->Void): jQueryObject;

	public function fadeTo(?duration: String, ?opacity: Float, ?arg3: Void->Void, ?_callback: Void->Void): jQueryObject;

	public function fadeToggle(?duration: String, ?easing: String, ?_callback: Void->Void): jQueryObject;

	public function filter(arg1: jQuerySelector): jQueryObject;

	public function find(selector: jQuerySelector): jQueryObject;

	public function first(): jQueryObject;

	public function focus(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function focusin(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function focusout(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function get(?index: Float): Element;

	public function has(arg1: String): jQueryObject;

	public function hasClass(className: String): Bool;

	public function height(?arg1: String): Float;

	public function hide(?duration: String, ?arg2: Void->Void, ?_callback: Void->Void): jQueryObject;

	public function hover(arg1: jQuery.event->Void, ?handlerOut: jQuery.event->Void): jQueryObject;

	public function html(?arg1: String): String;

	public function index(?arg1: jQuerySelector): Float;

	public function innerHeight(): Float;

	public function innerWidth(): Float;

	public function insertAfter(target: jQuerySelector): jQueryObject;

	public function insertBefore(target: jQuerySelector): jQueryObject;

	public function is(selector: jQuerySelector): Bool;

	public function keydown(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function keypress(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function keyup(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function last(): jQueryObject;

	public var length: Float;

	public function live(eventType: String, arg2: Void->Void, ?handler: Void->Void): jQueryObject;

	public function load(?arg1: jQuery.event->Void, ?arg2: jQuery.event->Void, ?complete: String->String->XMLHttpRequest->Void): jQueryObject;

	public function map(_callback: Float->Element->Void): jQueryObject;

	public function mousedown(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function mouseenter(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function mouseleave(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function mousemove(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function mouseout(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function mouseover(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function mouseup(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function next(?selector: jQuerySelector): jQueryObject;

	public function nextAll(?selector: String): jQueryObject;

	public function nextUntil(?selector: jQuerySelector): jQueryObject;

	public function not(arg1: jQuerySelector): jQueryObject;

	public function offset(?arg1: Dynamic): Dynamic;

	public function offsetParent(): jQueryObject;

	public function one(eventType: String, ?eventData: Dynamic, ?handler: jQuery.event->Void): jQueryObject;

	public function outerHeight(?includeMargin: Bool): Float;

	public function outerWidth(?includeMargin: Bool): Float;

	public function parent(?selector: jQuerySelector): jQueryObject;

	public function parents(?selector: jQuerySelector): jQueryObject;

	public function parentsUntil(?selector: jQuerySelector): jQueryObject;

	public function position(): Dynamic;

	public function prepend(arg1: String): jQueryObject;

	public function prependTo(target: jQuerySelector): jQueryObject;

	public function prev(?selector: jQuerySelector): jQueryObject;

	public function prevAll(?selector: jQuerySelector): jQueryObject;

	public function prevUntil(?selector: jQuerySelector): jQueryObject;

	public function pushStack(elements: Array, ?name: String, ?args: Array): jQueryObject;

	public function queue(?queueName: String, ?arg2: Array): Array;

	public function ready(handler: Void->Void): jQueryObject;

	public function remove(?selector: String): jQueryObject;

	public function removeAttr(attributeName: String): jQueryObject;

	public function removeClass(?arg1: String): jQueryObject;

	public function removeData(?name: String): jQueryObject;

	public function replaceAll(): jQueryObject;

	public function replaceWith(arg1: String): jQueryObject;

	public function resize(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function scroll(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function scrollLeft(?value: Float): Float;

	public function scrollTop(?value: Float): Float;

	public function select(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public var selector: String;

	public function serialize(): String;

	public function serializeArray(): Array;

	public function show(?duration: String, ?arg2: Void->Void, ?_callback: Void->Void): jQueryObject;

	public function siblings(?selector: jQuerySelector): jQueryObject;

	public function size(): Float;

	public function slice(start: Float, ?end: Float): jQueryObject;

	public function slideDown(?optionsOrDuration: Dynamic<Dynamic>, ?completeOrEasing: Void->Void, ?complete: Void->Void): jQueryObject;

	public function slideToggle(?optionsOrDuration: Dynamic<Dynamic>, ?completeOrEasing: Void->Void, ?complete: Void->Void): jQueryObject;

	public function slideUp(?optionsOrDuration: Dynamic<Dynamic>, ?completeOrEasing: Void->Void, ?complete: Void->Void): jQueryObject;

	public function stop(?clearQueue: Bool, ?jumpToEnd: Bool): jQueryObject;

	public function submit(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function text(?arg1: String): String;

	public function toArray(): Array;

	public function toggle(?arg1: jQuery.event->Void, ?arg2: jQuery.event->Void, ?arg3: jQuery.event->Void): jQueryObject;

	public function toggleClass(arg1: String, ?flag: Bool): jQueryObject;

	public function trigger(arg1: String, ?extraParameters: Array): jQueryObject;

	public function triggerHandler(eventType: String, extraParameters: Array): Dynamic;

	public function unbind(?arg1: String, ?arg2: jQuery.event->Void): jQueryObject;

	public function undelegate(?selector: String, ?eventType: String, ?handler: Void->Void): jQueryObject;

	public function unload(?arg1: jQuery.event->Void, ?handler: jQuery.event->Void): jQueryObject;

	public function unwrap(): jQueryObject;

	public function val(?arg1: String): String;

	public function width(?arg1: String): Float;

	public function wrap(arg1: String): jQueryObject;

	public function wrapAll(wrappingElement: String): jQueryObject;

	public function wrapInner(arg1: String): jQueryObject;
}
