/**
  JQuerySelector : generated by hxtern
*/
package ;
@:native("jQuerySelector")
extern typedef JQuerySelector = Hxtern.Any6<Window,js.html.Document,js.html.Element,Array<js.html.Element>,String,JQueryObject>

