/**
DirectionsService : generated by hxtern
*/
package google.maps;

extern class DirectionsService {
	public function new() {}

	public function route(request: Hxtern.Any2<google.maps.DirectionsRequest,Dynamic<Dynamic>>, _callback: google.maps.DirectionsResult->google.maps.DirectionsStatus->Void): Null<Dynamic> {}
}
