/**
DistanceMatrixService : generated by hxtern
*/
package google.maps;

class DistanceMatrixService{
	public function new();

	public function getDistanceMatrix(request: google.maps.DistanceMatrixRequest, _callback: google.maps.DistanceMatrixResponse->google.maps.DistanceMatrixStatus->Void): ;
}
