/**
  DistanceMatrixStatus : generated by hxtern
*/
package google.maps;

extern class DistanceMatrixStatus {
	public static var INVALID_REQUEST: Dynamic;

	public static var MAX_DIMENSIONS_EXCEEDED: Dynamic;

	public static var MAX_ELEMENTS_EXCEEDED: Dynamic;

	public static var OK: Dynamic;

	public static var OVER_QUERY_LIMIT: Dynamic;

	public static var REQUEST_DENIED: Dynamic;

	public static var UNKNOWN_ERROR: Dynamic;
}
