/**
DistanceMatrixService : generated by hxtern
*/
package google.maps;

extern class DistanceMatrixService{
	public function new();

	public function getDistanceMatrix(request: Hxtern.Any2<google.maps.DistanceMatrixRequest,Dynamic<Dynamic>>, _callback: google.maps.DistanceMatrixResponse->google.maps.DistanceMatrixStatus->Void): Null<Dynamic> {}
}
