/**
FusionTablesQuery : generated by hxtern
*/
package google.maps;

extern class FusionTablesQuery{
	public function new();

	public var from: String;

	public var select: String;

	public var where: String;
}
