/**
FusionTablesStyle : generated by hxtern
*/
package google.maps;

extern class FusionTablesStyle{
	public function new();

	public var markerOptions: Hxtern.Any2<google.maps.FusionTablesMarkerOptions,Dynamic<Dynamic>>;

	public var polygonOptions: Hxtern.Any2<google.maps.FusionTablesPolygonOptions,Dynamic<Dynamic>>;

	public var polylineOptions: Hxtern.Any2<google.maps.FusionTablesPolylineOptions,Dynamic<Dynamic>>;

	public var where: String;
}
