/**
  GeocoderLocationType : generated by hxtern
*/
package google.maps;

extern class GeocoderLocationType {
	public static var APPROXIMATE: Dynamic;

	public static var GEOMETRIC_CENTER: Dynamic;

	public static var RANGE_INTERPOLATED: Dynamic;

	public static var ROOFTOP: Dynamic;
}
