/**
GeocoderResult : generated by hxtern
*/
package google.maps;

extern class GeocoderResult {
	public function new() {}

	public var address_components: Array<google.maps.GeocoderAddressComponent>;

	public var formatted_address: String;

	public var geometry: google.maps.GeocoderGeometry;

	public var types: Array<String>;
}
