/**
MapOptions : generated by hxtern
*/
package google.maps;

class MapOptions{
	public function new();

	public var backgroundColor: String;

	public var center: google.maps.LatLng;

	public var disableDefaultUI: Bool;

	public var disableDoubleClickZoom: Bool;

	public var draggable: Bool;

	public var draggableCursor: String;

	public var draggingCursor: String;

	public var heading: Float;

	public var keyboardShortcuts: Bool;

	public var mapTypeControl: Bool;

	public var mapTypeControlOptions: google.maps.MapTypeControlOptions;

	public var mapTypeId: google.maps.MapTypeId;

	public var maxZoom: Float;

	public var minZoom: Float;

	public var noClear: Bool;

	public var overviewMapControl: Bool;

	public var overviewMapControlOptions: google.maps.OverviewMapControlOptions;

	public var panControl: Bool;

	public var panControlOptions: google.maps.PanControlOptions;

	public var rotateControl: Bool;

	public var rotateControlOptions: google.maps.RotateControlOptions;

	public var scaleControl: Bool;

	public var scaleControlOptions: google.maps.ScaleControlOptions;

	public var scrollwheel: Bool;

	public var streetView: google.maps.StreetViewPanorama;

	public var streetViewControl: Bool;

	public var streetViewControlOptions: google.maps.StreetViewControlOptions;

	public var styles: Array<google.maps.MapTypeStyle>;

	public var tilt: Float;

	public var zoom: Float;

	public var zoomControl: Bool;

	public var zoomControlOptions: google.maps.ZoomControlOptions;
}
