/**
PathElevationRequest : generated by hxtern
*/
package google.maps;

class PathElevationRequest{
	public function new();

	public var path: Array<google.maps.LatLng>;

	public var samples: Float;
}
