/**
StyledMapType : generated by hxtern
*/
package google.maps;

class StyledMapType{
	public function new(styles: Array<google.maps.MapTypeStyle>, ?opt_options: hxtern.Any2<google.maps.StyledMapTypeOptions,Dynamic<Dynamic>>);
}
