/**
  Iframer : generated by hxtern
*/
package ;
@:native("iframer")
extern class Iframer {
	public static function send(message: String, ?opt_data: Dynamic, ?opt_callback: Dynamic, ?opt_filter: Dynamic): Void {}
}
