/**
  Window : generated by hxtern
*/
package ;

extern class Window{
	/**
	  Inside an iframe, the properties of the iframer object are the data and
	  functions provided in iframes.open.
	 */
	public var iframer: hxtern.Any.Any2<Dynamic,Null<Dynamic>>;

	/**
	  The namespace for most of the APIs.
	  
	  This has "|undefined" so that JSCompiler won't optimize out existence checks
	  for win.iframes.
	 */
	public var iframes: hxtern.Any.Any2<iframes.Iframes,Null<Dynamic>>;
}
