/**
browser_ : generated by hxtern
This type is used interally to define the jQuery.browser subtype
*/
package jQuery;
@:native("jQuery.browser_")
extern class Browser_ {
	private function new() {}
}
