/**
support_ : generated by hxtern
This type is used interally to define the jQuery.support subtype
*/
package jQuery;
@:native("jQuery.support_")
extern class Support_ {
	private function new() {}

	public var boxModel: Bool;

	public var changeBubbles: Bool;

	public var cssFloat: Bool;

	public var hrefNormalized: Bool;

	public var htmlSerialize: Bool;

	public var leadingWhitespace: Bool;

	public var noCloneEvent: Bool;

	public var opacity: Bool;

	public var scriptEval: Bool;

	public var style: Bool;

	public var submitBubbles: Bool;

	public var tbody: Bool;
}
