/**
  FeatureStyle : generated by hxtern
*/
package google.maps.visualization;

class FeatureStyle{
	public function new();

	public var fillColor: String;

	public var fillOpacity: String;

	public var iconAnchor: String;

	public var iconClip: String;

	public var iconImage: String;

	public var iconOpacity: String;

	public var iconSize: String;

	public function reset(property: String): ;

	public function resetAll(): ;

	public var strokeColor: String;

	public var strokeOpacity: String;

	public var strokeWidth: String;

	public var zIndex: String;
}
