/**
  AdUnitOptions : generated by hxtern
*/
package google.maps.adsense;

extern class AdUnitOptions {
	public function new() {}

	public var backgroundColor: String;

	public var borderColor: String;

	public var channelNumber: String;

	public var format: google.maps.adsense.AdFormat;

	public var map: google.maps.Map;

	public var position: google.maps.ControlPosition;

	public var publisherId: String;

	public var textColor: String;

	public var titleColor: String;

	public var urlColor: String;
}
