/**
  AcceptsOption : generated by hxtern
*/
package chrome.fileSystem;

extern typedef AcceptsOption = {description: Hxtern.Any2<String,Null<Dynamic>>, mimeTypes: Hxtern.Any2<Array<String>,Null<Dynamic>>, extensions: Hxtern.Any2<Array<String>,Null<Dynamic>>}

