/**
  ChooseEntryOptions : generated by hxtern
*/
package chrome.fileSystem;

extern typedef ChooseEntryOptions = {type: Hxtern.Any2<String,Null<Dynamic>>, suggestedName: Hxtern.Any2<String,Null<Dynamic>>, accepts: Hxtern.Any2<Array<chrome.fileSystem.AcceptsOption>,Null<Dynamic>>, acceptsAllTypes: Hxtern.Any2<Bool,Null<Dynamic>>, acceptsMultiple: Hxtern.Any2<Bool,Null<Dynamic>>}

