/**
GadgetHolder : generated by hxtern
*/
package google.container;

extern class GadgetHolder{
	public function new(siteId: Float, el: js.html.Element);

	public function dispose(): Void {}

	public function getElement(): js.html.Element {}

	public function getGadgetInfo(): Dynamic {}

	public function getIframeElement(): js.html.Element {}

	public function getIframeId(): String {}

	public function getUrl(): String {}

	public function getView(): String {}

	public function onConstructed(): Void {}

	public function render(gadgetInfo: Dynamic, gadgetParams: Dynamic, renderParams: Dynamic): Void {}

	public function setSecurityToken(value: String): Void {}
}
