/**
GadgetHolder : generated by hxtern
*/
package google.container;

class GadgetHolder{
	public function new(siteId: Float, el: Element);

	public function dispose(): Void;

	public function getElement(): Element;

	public function getGadgetInfo(): Dynamic;

	public function getIframeElement(): Element;

	public function getIframeId(): String;

	public function getUrl(): String;

	public function getView(): String;

	public function onConstructed(): Void;

	public function render(gadgetInfo: Dynamic, gadgetParams: Dynamic, renderParams: Dynamic): Void;

	public function setSecurityToken(value: String): Void;
}
