/**
queryObject : generated by hxtern
This object is not constructed directly. It is returned by calls to
FB.Data.Query.
*/

@:native("FB.Data.queryObject")
class QueryObject{
	public function new();
}
