/**
  FB : generated by hxtern
*/
package ;

extern class FB {
	public static function api(path: String, ?method: Hxtern.Any3<String,Dynamic<Dynamic>,Dynamic<Dynamic>->Void>, ?params: Hxtern.Any2<Dynamic<Dynamic>,Dynamic<Dynamic>->Void>, ?_callback: Dynamic<Dynamic>->Void): Void {}

	public static function getLoginStatus(_callback: Dynamic<Dynamic>->Void, ?force: Bool): Void {}

	public static function getSession(): Dynamic<Dynamic> {}

	public static function init(?opt_opts: Dynamic<Dynamic>): Void {}

	public static function login(_callback: Dynamic<Dynamic>->Void, ?opt_opts: Dynamic<Dynamic>): Void {}

	public static function logout(?_callback: Dynamic<Dynamic>->Void): Void {}

	public static function ui(params: Dynamic<Dynamic>, ?_callback: Dynamic<Dynamic>->Void): Void {}
}
/**
  Canvas : generated by hxtern
*/


extern class Canvas {
	public static function getPageInfo(_callback: Dynamic<Dynamic>->Void): Void {}

	public static function setAutoResize(?onOrOff: Hxtern.Any2<Bool,Float>, ?interval: Float): Void {}

	public static function setSize(params: Dynamic<Float>): Void {}
}
/**
  Data : generated by hxtern
*/


extern class Data {
	public static function query(template: String, ?_opt0: Hxtern.Any3<String,Float,FB.QueryObject>, ?_opt1: Hxtern.Any3<String,Float,FB.QueryObject>, ?_opt2: Hxtern.Any3<String,Float,FB.QueryObject>, ?_opt3: Hxtern.Any3<String,Float,FB.QueryObject>, ?_opt4: Hxtern.Any3<String,Float,FB.QueryObject>, ?_opt5: Hxtern.Any3<String,Float,FB.QueryObject>): FB.QueryObject {}

	public static function waitOn(dependencies: Array<Dynamic>, _callback: Dynamic<Dynamic>->Void): Dynamic<Dynamic> {}
}
/**
queryObject : generated by hxtern
This object is not constructed directly. It is returned by calls to
FB.Data.Query.
*/

@:native("FB.Data.queryObject")
extern class QueryObject {
	private function new() {}
}
/**
  Event : generated by hxtern
*/


extern class Event {
	public static function subscribe(eventName: String, _callback: Dynamic<Dynamic>->Void): Void {}

	public static function unsubscribe(eventName: String, _callback: Dynamic<Dynamic>->Void): Void {}
}
/**
  XFBML : generated by hxtern
*/


extern class XFBML {
	public static function parse(?node: js.html.Element, ?_callback: Dynamic<Dynamic>->Void): Void {}
}
