/**
FusionTablesLayerOptions : generated by hxtern
*/
package google.maps;

class FusionTablesLayerOptions{
	public function new();

	public var clickable: Bool;

	public var heatmap: Bool;

	public var map: google.maps.Map;

	public var query: String;

	public var suppressInfoWindows: Bool;
}
