/**
MaxZoomService : generated by hxtern
*/
package google.maps;

extern class MaxZoomService {
	public function new() {}

	public function getMaxZoomAtLatLng(latlng: google.maps.LatLng, _callback: google.maps.MaxZoomResult->Void): Null<Dynamic> {}
}
