/**
ScaleControlOptions : generated by hxtern
*/
package google.maps;

class ScaleControlOptions{
	public function new();

	public var position: google.maps.ControlPosition;

	public var style: google.maps.ScaleControlStyle;
}
