/**
Size : generated by hxtern
*/
package google.maps;

extern class Size {
	public function new(width: Float, height: Float, ?opt_widthUnit: String, ?opt_heightUnit: String) {}

	public function equals(other: google.maps.Size): Bool {}

	public var height: Float;

	public function toString(): String {}

	public var width: Float;
}
