/**
StyledMapType : generated by hxtern
*/
package google.maps;

class StyledMapType{
	public function new(style: Array<google.maps.MapTypeStyle>, ?opt_options: google.maps.StyledMapTypeOptions);

	public function bindTo(key: String, target: google.maps.MVCObject, ?opt_targetKey: String, ?opt_noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setValues(values: Dynamic): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
