/**
  Maps : generated by hxtern
*/
package google;
@:native("google.maps")
extern class Maps{
	public static var adsense: Dynamic;

	public static var Animation: Dynamic;

	public static var ControlPosition: Dynamic;

	public static var DirectionsStatus: Dynamic;

	public static var DistanceMatrixElementStatus: Dynamic;

	public static var DistanceMatrixStatus: Dynamic;

	public static var ElevationStatus: Dynamic;

	public static var event: Dynamic;

	public static var GeocoderLocationType: Dynamic;

	public static var GeocoderStatus: Dynamic;

	public static var geometry: Dynamic;

	public static var MapTypeControlStyle: Dynamic;

	public static var MapTypeId: Dynamic;

	public static var MaxZoomStatus: Dynamic;

	public static var panoramio: Dynamic;

	public static var ScaleControlStyle: Dynamic;

	public static var StreetViewStatus: Dynamic;

	public static var TravelMode: Dynamic;

	public static var UnitSystem: Dynamic;

	public static var ZoomControlStyle: Dynamic;
}
