/**
  DirectionsWaypoint : generated by hxtern
*/
package google.maps;

extern class DirectionsWaypoint {
	public function new() {}

	public var location: Hxtern.Any2<google.maps.LatLng,String>;

	public var stopover: Bool;
}
