/**
  DistanceMatrixResponseElement : generated by hxtern
*/
package google.maps;

extern class DistanceMatrixResponseElement {
	public function new() {}

	public var distance: google.maps.Distance;

	public var duration: google.maps.Duration;

	public var status: google.maps.DistanceMatrixElementStatus;
}
