/**
  ElevationResult : generated by hxtern
*/
package google.maps;

extern class ElevationResult {
	public function new() {}

	public var elevation: Float;

	public var location: google.maps.LatLng;

	public var resolution: Float;
}
