/**
  FusionTablesMouseEvent : generated by hxtern
*/
package google.maps;

extern class FusionTablesMouseEvent {
	public function new() {}

	public var infoWindowHtml: String;

	public var latLng: google.maps.LatLng;

	public var pixelOffset: google.maps.Size;

	public var row: Dynamic<google.maps.FusionTablesCell>;
}
