/**
ImageMapType : generated by hxtern
*/
package google.maps;

class ImageMapType{
	public function new(opts: Dynamic);

	public function addListener(eventName: String, handler: Dynamic): google.maps.MapsEventListener;

	public var alt: String;

	public function bindTo(key: String, target: google.maps.MVCObject, ?opt_targetKey: String, ?opt_noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function getOpacity(): Float;

	public function getTile(tileCoord: google.maps.Point, zoom: Float, ownerDocument: Document): Node;

	public var maxZoom: Float;

	public var minZoom: Float;

	public var name: String;

	public function notify(key: String): ;

	public var projection: google.maps.Projection;

	public var radius: Float;

	public function releaseTile(tile: Node): ;

	public function set(key: String, value: Dynamic): ;

	public function setOpacity(opacity: Float): ;

	public function setValues(values: Dynamic): ;

	public var tileSize: google.maps.Size;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
