/**
  StreetViewLink : generated by hxtern
*/
package google.maps;

extern class StreetViewLink {
	public function new() {}

	public var description: String;

	public var heading: Float;

	public var pano: String;
}
