/**
  StyledMapTypeOptions : generated by hxtern
*/
package google.maps;

extern class StyledMapTypeOptions {
	public function new() {}

	public var alt: String;

	public var maxZoom: Float;

	public var minZoom: Float;

	public var name: String;
}
