/**
  TransitLine : generated by hxtern
*/
package google.maps;

extern class TransitLine {
	public function new() {}

	public var agencies: Array<google.maps.TransitAgency>;

	public var color: String;

	public var icon: String;

	public var name: String;

	public var short_name: String;

	public var text_color: String;

	public var url: String;

	public var vehicle: google.maps.TransitVehicle;
}
