/**
IceCandidate : generated by hxtern
TODO(bemasc): Remove this definition once it is removed from the browser.
*/
package ;

class IceCandidate{
	public function new(label: String, sdp: String);

	public var label: String;

	public function toSdp(): String;
}
