/**
  MediaStreamConstraintsInterface_ : generated by hxtern
*/
package ;

extern class MediaStreamConstraintsInterface_{
	public function new();

	public var audio: Hxtern.Any2<Bool,MediaTrackConstraints>;

	public var video: Hxtern.Any2<Bool,MediaTrackConstraints>;
}
