/**
  MediaTrackConstraintsInterface_ : generated by hxtern
*/
package ;

extern class MediaTrackConstraintsInterface_ {
	public function new() {}

	public var mandatory: MediaTrackConstraintSet;

	public var optional: Array<MediaTrackConstraintSet>;
}
