/**
  MediaConstraintsInterface_ : generated by hxtern
*/
package ;

class MediaConstraintsInterface_{
	public var mandatory: MediaConstraintSet_;

	public var optional: Array<MediaConstraintSet_>;
}
