/**
  MediaTrackConstraintSetInterface_ : generated by hxtern
*/
package ;

extern class MediaTrackConstraintSetInterface_{
	public function new() {}

	public var maxAspectRatio: Float;

	public var maxFrameRate: Float;

	public var maxHeight: Float;

	public var maxWidth: Float;

	public var minAspectRatio: Float;

	/**
	  Due to a typo, this is called "minFramerate" in the -01 draft.
	 */
	public var minFrameRate: Float;

	public var minHeight: Float;

	public var minWidth: Float;
}
