/**
  MediaStreamConstraintsInterface_ : generated by hxtern
*/
package ;

class MediaStreamConstraintsInterface_{
	public var audio: hxtern.Any2<Bool,MediaTrackConstraints>;

	public var video: hxtern.Any2<Bool,MediaTrackConstraints>;
}
