/**
  MediaConstraintsInterface_ : generated by hxtern
*/
package ;

extern class MediaConstraintsInterface_ {
	public function new() {}

	public var mandatory: MediaConstraintSet_;

	public var optional: Array<MediaConstraintSet_>;
}
