/**
  MediaConstraintSetInterface_ : generated by hxtern
*/
package ;

extern class MediaConstraintSetInterface_ {
	public function new() {}

	public var DtlsSrtpKeyAgreement: Bool;

	public var OfferToReceiveAudio: Bool;

	public var OfferToReceiveVideo: Bool;

	public var RtpDataChannels: Bool;
}
