/**
  MediaTrackConstraintsInterface_ : generated by hxtern
*/
package ;

class MediaTrackConstraintsInterface_{
	public var mandatory: MediaTrackConstraintSet;

	public var optional: Array<MediaTrackConstraintSet>;
}
