/**
  Navigator : generated by hxtern
*/
package ;

extern class Navigator{
	public function webkitGetUserMedia(constraints: MediaStreamConstraints, successCallback: MediaStream->Void, ?errorCallback: NavigatorUserMediaError->Void): Void {}
}
