/**
  NavigatorUserMediaError : generated by hxtern
*/
package ;

class NavigatorUserMediaError{
	public function new();

	public var code: Float;

	public var constraintName: String;

	public var message: String;

	public var name: String;
}
