/**
  RTCDataChannel : generated by hxtern
*/
package ;

class RTCDataChannel{
	public var binaryType: String;

	public var bufferedAmount: Float;

	public function close(): Void;

	public var onclose: Event->Void;

	public var onerror: Event->Void;

	public var onmessage: MessageEvent->Void;

	public var onopen: Event->Void;

	/**
	  An enumerated string type (RTCDataChannelState) with values:
	  "connecting", "open", "closing", and "closed".
	 */
	public var readyState: String;

	public function send(data: Dynamic): Void;
}
