/**
RTCSessionDescription : generated by hxtern
*/
package ;

class RTCSessionDescription{
	public function new(?descriptionInitDict: Dynamic);

	public var sdp: String;

	public var type: RTCSdpType;
}
