/**
AutocompleteService : generated by hxtern
*/
package google.maps.places;

class AutocompleteService{
	public function new();

	public function getPlacePredictions(request: Dynamic, _callback: Array<google.maps.places.AutocompletePrediction>->google.maps.places.PlacesServiceStatus->Void): ;

	public function getQueryPredictions(request: Dynamic, _callback: Array<google.maps.places.QueryAutocompletePrediction>->google.maps.places.PlacesServiceStatus->Void): ;
}
