/**
  AutocompletionRequest : generated by hxtern
*/
package google.maps.places;

extern class AutocompletionRequest {
	public function new() {}

	public var bounds: google.maps.LatLngBounds;

	public var componentRestrictions: google.maps.places.ComponentRestrictions;

	public var input: String;

	public var location: google.maps.LatLng;

	public var offset: Float;

	public var radius: Float;

	public var types: Array<String>;
}
