/**
  PlacePhoto : generated by hxtern
*/
package google.maps.places;

class PlacePhoto{
	public function new();

	public function getUrl(opts: google.maps.places.PhotoOptions): String;

	public var height: Float;

	public var html_attributions: Array<String>;

	public var width: Float;
}
