/**
  PlacePhoto : generated by hxtern
*/
package google.maps.places;

class PlacePhoto{
	public function new();

	public function getUrl(opts: Dynamic): String;

	public var height: Float;

	public var html_attributions: Array<String>;

	public var width: Float;
}
