/**
  QueryAutocompletionRequest : generated by hxtern
*/
package google.maps.places;

extern class QueryAutocompletionRequest {
	public function new() {}

	public var bounds: google.maps.LatLngBounds;

	public var input: String;

	public var location: google.maps.LatLng;

	public var offset: Float;

	public var radius: Float;
}
