/**
AnnotatedTimeLine : generated by hxtern
*/
package google.visualization;

extern class AnnotatedTimeLine {
	public function new(container: Node) {}

	public function draw(data: Dynamic, ?opt_options: Dynamic): Null<Dynamic> {}

	public function getSelection(): Array<Dynamic> {}

	public function getVisibleChartRange(): Dynamic {}

	public function hideDataColumns(columnIndexes: Hxtern.Any2<Float,Array<Float>>): Null<Dynamic> {}

	public function setSelection(?opt_selection: Hxtern.Any3<Array<Dynamic>,Array,?Dynamic>): Null<Dynamic> {}

	public function setVisibleChartRange(firstDate: Date, lastDate: Date): Null<Dynamic> {}

	public function showDataColumns(columnIndexes: Hxtern.Any2<Float,Array<Float>>): Null<Dynamic> {}
}
