/**
BarFormat : generated by hxtern
*/
package google.visualization;

extern class BarFormat {
	public function new(?opt_options: Dynamic) {}

	public function format(dataTable: google.visualization.DataTable, columnIndex: Float): Null<Dynamic> {}
}
