/**
ChartWrapper : generated by hxtern
*/
package google.visualization;

extern class ChartWrapper {
	public function new(?opt_specification: Hxtern.Any2<Dynamic,String>) {}

	public function clone(): google.visualization.ChartWrapper {}

	public function draw(?opt_container: Node): Null<Dynamic> {}

	public function getChart(): Dynamic {}

	public function getChartName(): String {}

	public function getChartType(): String {}

	public function getContainerId(): String {}

	public function getDataSourceUrl(): String {}

	public function getDataTable(): google.visualization.DataTable {}

	public function getOption(key: String, ?opt_default: Dynamic): Void {}

	public function getOptions(): Dynamic {}

	public function getQuery(): String {}

	public function getRefreshInterval(): Float {}

	public function getView(): Hxtern.Any2<google.visualization.DataView,Array<google.visualization.DataView>> {}

	public function setChartName(chartName: String): Null<Dynamic> {}

	public function setChartType(chartType: String): Null<Dynamic> {}

	public function setContainerId(containerId: String): Null<Dynamic> {}

	public function setDataSourceUrl(dataSourceUrl: String): Null<Dynamic> {}

	public function setDataTable(dataTable: Hxtern.Any3<?Dynamic,String,google.visualization.DataTable>): Null<Dynamic> {}

	public function setOption(key: String, value: Dynamic): Void {}

	public function setOptions(options: Dynamic): Void {}

	public function setQuery(query: String): Null<Dynamic> {}

	public function setRefreshInterval(refreshInterval: Float): Null<Dynamic> {}

	public function setView(view: Hxtern.Any3<String,google.visualization.DataView,Array<google.visualization.DataView>>): Null<Dynamic> {}

	public function toJSON(): String {}
}
