/**
ChartEditor : generated by hxtern
*/
package google.visualization;

extern class ChartEditor {
	public function new(?opt_config: Dynamic) {}

	public function closeDialog(): ?Dynamic {}

	public function getChartWrapper(): google.visualization.ChartWrapper {}

	public function openDialog(chartWrapper: google.visualization.ChartWrapper, ?opt_options: Dynamic): ?Dynamic {}

	public function setChartWrapper(chartWrapper: google.visualization.ChartWrapper): ?Dynamic {}
}
