/**
ColorFormat : generated by hxtern
*/
package google.visualization;

extern class ColorFormat {
	public function new() {}

	public function addGradientRange(from: Dynamic, to: Dynamic, color: String, fromBgColor: String, toBgColor: String): Null<Dynamic> {}

	public function addRange(from: Dynamic, to: Dynamic, color: String, bgcolor: String): Null<Dynamic> {}

	public function format(dataTable: google.visualization.DataTable, columnIndex: Float): Null<Dynamic> {}
}
