/**
ControlWrapper : generated by hxtern
*/
package google.visualization;

extern class ControlWrapper {
	public function new(?opt_specification: Hxtern.Any2<Dynamic,String>) {}

	public function clone(): google.visualization.ControlWrapper {}

	public function draw(?opt_container: Node): Null<Dynamic> {}

	public function getContainerId(): String {}

	public function getControl(): Dynamic {}

	public function getControlName(): String {}

	public function getControlType(): String {}

	public function getOption(key: String, ?opt_default: Dynamic): Void {}

	public function getOptions(): Dynamic {}

	public function getState(): Dynamic {}

	public function setContainerId(containerId: String): Null<Dynamic> {}

	public function setControlName(controlName: String): Null<Dynamic> {}

	public function setControlType(controlType: String): Null<Dynamic> {}

	public function setOption(key: String, value: Dynamic): Void {}

	public function setOptions(options: Dynamic): Void {}

	public function setState(state: Dynamic): Void {}

	public function toJSON(): String {}
}
