/**
Dashboard : generated by hxtern
*/
package google.visualization;

extern class Dashboard {
	public function new(container: Node) {}

	public function bind(controls: Hxtern.Any2<google.visualization.ControlWrapper,Array<google.visualization.ControlWrapper>>, charts: Hxtern.Any2<google.visualization.ChartWrapper,Array<google.visualization.ChartWrapper>>): Void {}

	public function draw(dataTable: Hxtern.Any3<String,google.visualization.DataTable,google.visualization.DataView>): Void {}
}
