/**
DataView : generated by hxtern
*/
package google.visualization;

extern class DataView {
	public function new(dataTable: google.visualization.DataTable) {}

	public static function fromJSON(dataTable: google.visualization.DataTable, view: String): google.visualization.DataView {}

	public function getColumnId(columnIndex: Float): String {}

	public function getColumnLabel(columnIndex: Float): String {}

	public function getColumnPattern(columnIndex: Float): String {}

	public function getColumnProperties(columnIndex: Float): Dynamic {}

	public function getColumnProperty(columnIndex: Float, property: String): String {}

	public function getColumnRange(columnIndex: Float): Dynamic {}

	public function getColumnRole(columnIndex: Float): String {}

	public function getColumnType(columnIndex: Float): String {}

	public function getDistinctValues(columnIndex: Float): Array<Dynamic> {}

	public function getFilteredRows(columnFilters: Array<Dynamic>): Array<Float> {}

	public function getFormattedValue(rowIndex: Float, columnIndex: Float): String {}

	public function getNumberOfColumns(): Float {}

	public function getNumberOfRows(): Float {}

	public function getProperties(rowIndex: Float, columnIndex: Float): Dynamic {}

	public function getProperty(rowIndex: Float, columnIndex: Float, property: String): Dynamic {}

	public function getRowProperties(rowIndex: Float): Dynamic {}

	public function getRowProperty(rowIndex: Float, property: String): Dynamic {}

	public function getSortedRows(sortColumns: Hxtern.Any4<Float,Dynamic,Array<Float>,Array<Dynamic>>): Array<Float> {}

	public function getTableColumnIndex(viewColumnIndex: Float): Float {}

	public function getTableProperties(): Dynamic {}

	public function getTableProperty(property: String): Dynamic {}

	public function getTableRowIndex(viewRowIndex: Float): Float {}

	public function getValue(rowIndex: Float, columnIndex: Float): Dynamic {}

	public function getViewColumnIndex(tableColumnIndex: Float): Float {}

	public function getViewColumns(): Array<Float> {}

	public function getViewRowIndex(tableRowIndex: Float): Float {}

	public function getViewRows(): Array<Float> {}

	public function hideColumns(colIndices: Array<Float>): Null<Dynamic> {}

	public function hideRows(arg0: Hxtern.Any2<Float,Array<Float>>, ?opt_arg1: Float): Null<Dynamic> {}

	public function setColumns(colIndices: Array<Hxtern.Any2<Dynamic,Float>>): Null<Dynamic> {}

	public function setRows(arg0: Hxtern.Any2<Float,Array<Float>>, ?opt_arg1: Float): Null<Dynamic> {}

	public function toDataTable(): google.visualization.DataTable {}

	public function toJSON(): String {}
}
