/**
DateFormat : generated by hxtern
*/
package google.visualization;

extern class DateFormat {
	public function new(?opt_options: Dynamic) {}

	public function format(dataTable: google.visualization.DataTable, columnIndex: Float): Null<Dynamic> {}

	public function formatValue(value: Date): Dynamic {}
}
