/**
  Events : generated by hxtern
*/
package google.visualization;
@:native("google.visualization.events")
extern class Events {
	public static function addListener(eventSource: Dynamic, eventName: String, eventHandler: Dynamic): Dynamic {}

	public static function removeAllListeners(eventSource: Dynamic): Null<Dynamic> {}

	public static function removeListener(listener: Dynamic): Null<Dynamic> {}

	public static function trigger(eventSource: Dynamic, eventName: String, ?opt_eventDetails: Dynamic): Void {}
}
