/**
GadgetHelper : generated by hxtern
*/
package google.visualization;

extern class GadgetHelper{
	public function new();

	public function createQueryFromPrefs(prefs: Dynamic): google.visualization.Query {}

	public function validateResponse(response: google.visualization.QueryResponse): Bool {}
}
