/**
Gauge : generated by hxtern
*/
package google.visualization;

extern class Gauge{
	public function new(container: Node);

	public function clearChart(): Null<Dynamic> {}

	public function draw(data: Dynamic, ?opt_options: Dynamic): Null<Dynamic> {}
}
