/**
  IChart : generated by hxtern
*/
package google.visualization;

extern class IChart{
	public function new();

	public function clearChart(): Null<Dynamic> {}

	public function draw(data: Dynamic, ?opt_options: Dynamic): Null<Dynamic> {}

	public function getSelection(): Array<Dynamic> {}

	public function setSelection(?opt_selection: Hxtern.Any3<Array<Dynamic>,Array,?Dynamic>): Null<Dynamic> {}
}
