/**
ImageSparkLine : generated by hxtern
*/
package google.visualization;

extern class ImageSparkLine{
	public function new(container: Node);

	public function draw(data: Dynamic, ?opt_options: Dynamic): Null<Dynamic> {}

	public function getSelection(): Array<Dynamic> {}

	public function setSelection(?opt_selection: Hxtern.Any3<Array<Dynamic>,Array,?Dynamic>): Null<Dynamic> {}
}
