/**
ImageAreaChart : generated by hxtern
*/
package google.visualization;

extern class ImageAreaChart{
	public function new(container: Node);

	public function draw(data: Dynamic, ?opt_options: Dynamic): Null<Dynamic> {}
}
