/**
ImageChart : generated by hxtern
*/
package google.visualization;

extern class ImageChart{
	public function new(container: Node);

	public function draw(data: Dynamic, ?opt_options: Dynamic): Null<Dynamic> {}
}
