/**
MotionChart : generated by hxtern
*/
package google.visualization;

extern class MotionChart {
	public function new(container: Node) {}

	public function draw(data: Dynamic, ?opt_options: Dynamic): Null<Dynamic> {}

	public function getState(): Null<Dynamic> {}
}
