/**
NumberRangeFilter : generated by hxtern
*/
package google.visualization;

extern class NumberRangeFilter {
	public function new(container: Node) {}

	public function applyFilter(): Void {}

	public function draw(): Void {}

	public function getState(): Void {}

	public function resetControl(): Void {}
}
