/**
PatternFormat : generated by hxtern
*/
package google.visualization;

extern class PatternFormat {
	public function new(pattern: String) {}

	public function format(dataTable: google.visualization.DataTable, srcColumnIndices: Array<Float>, ?opt_dstColumnIndex: Float): Null<Dynamic> {}
}
