/**
PieChart : generated by hxtern
*/
package google.visualization;

extern class PieChart extends google.visualization.IChart {
	public function new(container: Node) {}

	public function clearChart(): Void {}

	public function draw(): Void {}

	public function getSelection(): Void {}

	public function setSelection(): Void {}
}
