/**
SparklineChart : generated by hxtern
*/
package google.visualization;

extern class SparklineChart{
	public function new(container: Node);

	public function clearChart(): Void {}

	public function draw(): Void {}

	public function getSelection(): Void {}

	public function setSelection(): Void {}
}
