/**
TreeMap : generated by hxtern
*/
package google.visualization;

extern class TreeMap{
	public function new(container: Node);

	public function clearChart(): Void {}

	public function draw(): Void {}

	public function getSelection(): Void {}

	public function goUpAndDraw(): Null<Dynamic> {}

	public function setSelection(): Void {}
}
