/**
  MediaConstraintSetInterface_ : generated by hxtern
*/


class MediaConstraintSetInterface_{
	public function new();
}
/**
  MediaConstraintsInterface_ : generated by hxtern
*/


class MediaConstraintsInterface_{
	public function new();
}
/**
  MediaStreamConstraintsInterface_ : generated by hxtern
*/


class MediaStreamConstraintsInterface_{
	public function new();
}
/**
  MediaStreamTrack : generated by hxtern
*/


class MediaStreamTrack{
	public function new();
}
/**
  MediaTrackConstraintSetInterface_ : generated by hxtern
*/


class MediaTrackConstraintSetInterface_{
	public function new();
}
/**
  MediaTrackConstraintsInterface_ : generated by hxtern
*/


class MediaTrackConstraintsInterface_{
	public function new();
}
/**
  NavigatorUserMediaError : generated by hxtern
*/


class NavigatorUserMediaError{
	public function new();
}
/**
  RTCConfigurationInterface_ : generated by hxtern
*/


class RTCConfigurationInterface_{
	public function new();
}
/**
  RTCDataChannel : generated by hxtern
*/


class RTCDataChannel{
	public function new();
}
/**
  RTCDataChannelInitInterface_ : generated by hxtern
*/


class RTCDataChannelInitInterface_{
	public function new();
}
/**
  RTCIceServerInterface_ : generated by hxtern
*/


class RTCIceServerInterface_{
	public function new();
}
/**
  RTCStatsReport : generated by hxtern
*/


class RTCStatsReport{
	public function new();
}
/**
  RTCStatsResponse : generated by hxtern
*/


class RTCStatsResponse{
	public function new();
}
/**
  SourceInfo : generated by hxtern
*/


class SourceInfo{
	public function new();
}
