/**
DemographicsLayer : generated by hxtern
*/
package google.maps.visualization;

class DemographicsLayer{
	public function new(?opt_opts: google.maps.visualization.DemographicsLayerOptions);

	public function getMap(): google.maps.Map;

	public function getQuery(): google.maps.visualization.DemographicsQuery;

	public function getStyle(): Array<google.maps.visualization.DemographicsStyle>;

	public function setMap(map: google.maps.Map): ;

	public function setOptions(options: google.maps.visualization.DemographicsLayerOptions): ;

	public function setQuery(query: google.maps.visualization.DemographicsQuery): ;

	public function setStyle(style: Array<google.maps.visualization.DemographicsStyle>): ;
}
