/**
DemographicsLayer : generated by hxtern
*/
package google.maps.visualization;

class DemographicsLayer{
	public function new(?opt_opts: hxtern.Any2<google.maps.visualization.DemographicsLayerOptions,Dynamic<String>>);

	public function getMap(): google.maps.Map;

	public function getQuery(): google.maps.visualization.DemographicsQuery;

	public function getStyle(): Array<google.maps.visualization.DemographicsStyle>;

	public function setMap(map: google.maps.Map): Null<Dynamic>;

	public function setOptions(options: hxtern.Any2<google.maps.visualization.DemographicsLayerOptions,Dynamic<String>>): Null<Dynamic>;

	public function setQuery(query: google.maps.visualization.DemographicsQuery): Null<Dynamic>;

	public function setStyle(style: Array<google.maps.visualization.DemographicsStyle>): Null<Dynamic>;
}
