/**
  DemographicsLayerOptions : generated by hxtern
*/
package google.maps.visualization;

class DemographicsLayerOptions{
	public function new();

	public var clickable: Bool;

	public var map: google.maps.Map;

	public var query: google.maps.visualization.DemographicsQuery;

	public var style: Array<google.maps.visualization.DemographicsStyle>;

	public var suppressInfoWindows: String;
}
