/**
GAdsManager : generated by hxtern
*/
package ;

class GAdsManager{
	public function new(map: GMap2, publisherId: String, ?adsManagerOptions: Dynamic<Dynamic>);

	public function disable(): Null<Dynamic> {}

	public function enable(): Null<Dynamic> {}
}
