/**
GControl : generated by hxtern
*/
package ;

class GControl{
	public function new(?printable: Bool, ?selectable: Bool);

	public function allowSetVisibility(): Bool;

	public function getDefaultPosition(): GControlPosition;

	public function initialize(map: GMap2): Node;

	public function printable(): Bool;

	public function selectable(): Bool;
}
