/**
GGroundOverlay : generated by hxtern
*/
package ;

extern class GGroundOverlay{
	public function new(imageUrl: String, bounds: GLatLngBounds);

	public function copy(): GOverlay {}

	public function getKml(_callback: String->Void): Void {}

	public function hide(): Null<Dynamic> {}

	public function initialize(map: GMap2): Void {}

	public function isHidden(): Bool {}

	public function redraw(force: Bool): Void {}

	public function remove(): Null<Dynamic> {}

	public function show(): Null<Dynamic> {}

	public function supportsHide(): Bool {}
}
