/**
GLayer : generated by hxtern
*/
package ;

class GLayer{
	public function new(layerId: String);

	public static function isHidden(layerId: String): Void;

	public function hide(): Null<Dynamic>;

	public function show(): Null<Dynamic>;
}
