/**
  GLog : generated by hxtern
*/
package ;

extern class GLog{
	public static function write(message: String, ?color: String): Void {}

	public static function writeHtml(html: String): Void {}

	public static function writeUrl(url: String): Void {}
}
