/**
GOverlay : generated by hxtern
*/
package ;

class GOverlay{
	public function new();

	public static function getZIndex(latitude: Float): Float {}

	public function copy(): GOverlay {}

	public function getKml(_callback: String->Void): Void {}

	public function initialize(map: GMap2): Void {}

	public function redraw(force: Bool): Void {}

	public function remove(): Null<Dynamic> {}
}
