/**
GPoint : generated by hxtern
*/
package ;

class GPoint{
	public function new(x: Float, y: Float);

	public function equals(other: GPoint): Bool;

	public function toString(): String;

	public var x: Float;

	public var y: Float;
}
