/**
  GProjection : generated by hxtern
*/
package ;

extern class GProjection{
	public function new() {}

	public function fromLatLngToPixel(latlng: GLatLng, zoom: Float): GPoint {}

	public function fromPixelToLatLng(pixel: GPoint, zoom: Float, ?unbounded: Bool): GLatLng {}

	public function getWrapWidth(zoom: Float): Float {}

	public function tileCheckRange(tile: GPoint, zoom: Float, tilesize: Float): Bool {}
}
