/**
GRoute : generated by hxtern
*/
package ;

class GRoute{
	public function new();

	public function getDistance(): Dynamic;

	public function getDuration(): Dynamic;

	public function getEndGeocode(): Dynamic;

	public function getEndLatLng(): GLatLng;

	public function getNumSteps(): Float;

	public function getStartGeocode(): Dynamic;

	public function getStep(i: Float): GStep;

	public function getSummaryHtml(): String;
}
