/**
GScreenPoint : generated by hxtern
*/
package ;

extern class GScreenPoint {
	public function new(x: Float, y: Float, ?xunits: String, ?yunits: String) {}

	public var x: Float;

	public var xunits: String;

	public var y: Float;

	public var yunits: String;
}
