/**
GScreenSize : generated by hxtern
*/
package ;

class GScreenSize{
	public function new(width: Float, height: Float, ?xunits: String, ?yunits: String);

	public var height: Float;

	public var width: Float;

	public var xunits: String;

	public var yunits: String;
}
