/**
GSmallZoomControl : generated by hxtern
*/
package ;

class GSmallZoomControl{
	public function new();

	public function allowSetVisibility(): Bool {}

	public function getDefaultPosition(): GControlPosition {}

	public function initialize(map: GMap2): Node {}

	public function printable(): Bool {}

	public function selectable(): Bool {}
}
