/**
GStreetviewOverlay : generated by hxtern
*/
package ;

extern class GStreetviewOverlay extends GOverlay {
	public function new() {}

	public function copy(): GOverlay {}

	public function getKml(_callback: String->Void): Void {}

	public function initialize(map: GMap2): Void {}

	public function redraw(force: Bool): Void {}

	public function remove(): Null<Dynamic> {}
}
