/**
GStreetviewLink : generated by hxtern
*/
package ;

extern class GStreetviewLink{
	private function new();

	public var description: String;

	public var panoId: String;

	public var yaw: Float;
}
