/**
GStreetviewClient : generated by hxtern
*/
package ;

class GStreetviewClient{
	public function new();

	public static var ReturnValues: Dynamic;

	public function getNearestPanorama(latlng: GLatLng, _callback: GStreetviewData->Void): Void;

	public function getNearestPanoramaLatLng(latlng: GLatLng, _callback: GLatLng->Void): Void;

	public function getPanoramaById(panoId: String, _callback: GStreetviewData->Void): Void;
}
/**
  GStreetviewClient : generated by hxtern
*/


class ReturnValues{
	public static var NO_NEARBY_PANO: Dynamic;

	public static var SERVER_ERROR: Dynamic;

	public static var SUCCESS: Dynamic;
}
