/**
GStreetviewData : generated by hxtern
*/
package ;

extern class GStreetviewData{
	private function new();

	public var code: GStreetviewClient.ReturnValues;

	public var copyright: String;

	public var links: Array<GStreetviewLink>;

	public var location: Dynamic<Dynamic>;
}
