/**
GXslt : generated by hxtern
*/
package ;

extern class GXslt {
	private function new() {}

	public static function create(xsltnode: Node): GXslt {}

	public static function transformToHtml(xmlnode: Node, htmlnode: Node): Bool {}
}
