/**
AutocompleteOptions : generated by hxtern
*/
package google.maps.places;

extern class AutocompleteOptions{
	public function new();

	public var bounds: google.maps.LatLngBounds;

	public var types: Array<String>;
}
