/**
  WeatherMouseEvent : generated by hxtern
*/
package google.maps.weather;

extern class WeatherMouseEvent {
	public function new() {}

	public var featureDetails: google.maps.weather.WeatherFeature;

	public var infoWindowHtml: String;

	public var latLng: google.maps.LatLng;

	public var pixelOffset: google.maps.Size;
}
