/**
  Storage : generated by hxtern
*/
package chrome.system;
@:native("chrome.system.storage")
class Storage{
	public static function ejectDevice(id: String, _callback: String->Void): Void;

	public static function getAvailableCapacity(id: String, _callback: Dynamic<Float>->Void): Void;

	public static function getInfo(_callback: Array<chrome.system.storage.StorageUnitInfo>->Void): Void;

	public static var onAttached: chrome.system.storage.StorageUnitInfoEvent;

	public static var onDetached: chrome.system.StringEvent;
}