/**
StringEvent : generated by hxtern
Event whose listeners take a string parameter.
*/
package chrome.system;

class StringEvent{
	public function new();

	public function addListener(_callback: String->Void): Void;

	public function hasListener(_callback: String->Void): Bool;

	public function hasListeners(): Bool;

	public function removeListener(_callback: String->Void): Void;
}
