/**
  TextSearchRequest : generated by hxtern
*/
package google.maps.places;

extern class TextSearchRequest {
	public function new() {}

	public var bounds: google.maps.LatLngBounds;

	public var location: google.maps.LatLng;

	public var query: String;

	public var radius: Float;

	public var types: Array<String>;
}
