/**
ConnectionHandle : generated by hxtern
*/
package chrome.usb;
class ConnectionHandle{
	public function new();

	public var handle: Float;

	public var productId: Float;

	public var vendorId: Float;
}