/**
  GenericTransferInfo : generated by hxtern
*/
package chrome.usb;

extern typedef GenericTransferInfo = {direction: String, endpoint: Float, length: Hxtern.Any2<Float,Null<Dynamic>>, data: Hxtern.Any2<ArrayBuffer,Null<Dynamic>>}

