/**
TransferResultInfo : generated by hxtern
*/
package chrome.usb;

extern class TransferResultInfo{
	public function new();

	public var data: Hxtern.Any2<ArrayBuffer,Null<Dynamic>>;

	public var resultCode: Hxtern.Any2<Float,Null<Dynamic>>;
}
