/**
Clock : generated by hxtern
*/
package jasmine;

extern class Clock{
	public function new();

	public static var installed: jasmine.Clock;

	public static function tick(ms: Float): Void {}

	public static function useMock(): Void {}

	public var nowMillis: Float;
}
