/**
  Global : generated by hxtern
*/
package jasmine;

class Global{
	public static function afterEach(handler: Void->Void): Void;

	public static function beforeEach(handler: Void->Void): Void;

	public static function describe(description: String, handler: Void->Void): Void;

	public static function expect(expectedValue: Dynamic): jasmine.Matcher;

	public static function inject(): Void;

	public static function it(description: String, handler: Void->Void): Void;

	public static function module(): Void;

	public static function runs(handler: Void->Void): Void;

	public static function spyOn(spiedOnObject: Dynamic, methodName: String): jasmine.Spy;

	public static function waits(timeout: Float): Void;

	public static function waitsFor(handler: Void->Bool, ?opt_message: String, ?opt_timeout: Float): Void;

	public static function xdescribe(description: String, handler: Void->Void): Void;

	public static function xit(description: String, handler: Void->Void): Void;
}
