/**
Helper : generated by hxtern
*/
package jasmine;

class Helper{
	public function new();

	public var actual: Dynamic;

	public function addMatchers(value: Dynamic): Void;

	public var isNot: Bool;

	public var message: hxtern.Any.Any2<Null<Dynamic>,Void->String>;
}
