/**
JsApiReporter : generated by hxtern
*/
package jasmine;

extern class JsApiReporter{
	public function new();

	public function getReport(): String {}

	public function getRunTime(): Float {}

	public function isFinished(): Bool {}

	public function isInitialized(): Bool {}

	public function isSuccess(): Bool {}
}
