/**
  DrawingManagerOptions : generated by hxtern
*/
package google.maps.drawing;

extern class DrawingManagerOptions {
	public function new() {}

	public var circleOptions: Hxtern.Any2<google.maps.CircleOptions,Dynamic<String>>;

	public var drawingControl: Bool;

	public var drawingControlOptions: Hxtern.Any2<google.maps.drawing.DrawingControlOptions,Dynamic<String>>;

	public var drawingMode: google.maps.drawing.OverlayType;

	public var map: google.maps.Map;

	public var markerOptions: Hxtern.Any2<google.maps.MarkerOptions,Dynamic<String>>;

	public var polygonOptions: Hxtern.Any2<google.maps.PolygonOptions,Dynamic<String>>;

	public var polylineOptions: Hxtern.Any2<google.maps.PolylineOptions,Dynamic<String>>;

	public var rectangleOptions: Hxtern.Any2<google.maps.RectangleOptions,Dynamic<String>>;
}
