/**
DirectionsRequest : generated by hxtern
*/
package google.maps;

class DirectionsRequest{
	public function new();

	public var avoidHighways: Bool;

	public var avoidTolls: Bool;

	public var destination: google.maps.LatLng;

	public var optimizeWaypoints: Bool;

	public var origin: google.maps.LatLng;

	public var provideRouteAlternatives: Bool;

	public var region: String;

	public var transitOptions: google.maps.TransitOptions;

	public var travelMode: google.maps.TravelMode;

	public var unitSystem: google.maps.UnitSystem;

	public var waypoints: Array<google.maps.DirectionsWaypoint>;
}
