/**
DistanceMatrixService : generated by hxtern
*/
package google.maps;

class DistanceMatrixService{
	public function new();

	public function getDistanceMatrix(request: hxtern.Any.Any2<google.maps.DistanceMatrixRequest,Dynamic<String>>, _callback: google.maps.DistanceMatrixResponse->google.maps.DistanceMatrixStatus->Void): Null<Dynamic>;
}
