/**
FusionTablesLayer : generated by hxtern
*/
package google.maps;

class FusionTablesLayer{
	public function new(options: hxtern.Any2<google.maps.FusionTablesLayerOptions,Dynamic<String>>);

	public function bindTo(key: String, target: google.maps.MVCObject, ?opt_targetKey: String, ?opt_noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function getMap(): google.maps.Map;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setMap(map: google.maps.Map): ;

	public function setOptions(options: hxtern.Any2<google.maps.FusionTablesLayerOptions,Dynamic<String>>): ;

	public function setValues(values: hxtern.Any2<Dynamic,>): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
