/**
GroundOverlay : generated by hxtern
*/
package google.maps;

class GroundOverlay{
	public function new(url: String, bounds: google.maps.LatLngBounds, ?opt_opts: Dynamic);

	public function bindTo(key: String, target: google.maps.MVCObject, ?opt_targetKey: String, ?opt_noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function getBounds(): google.maps.LatLngBounds;

	public function getMap(): google.maps.Map;

	public function getOpacity(): Float;

	public function getUrl(): String;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setMap(map: google.maps.Map): ;

	public function setOpacity(opacity: Float): ;

	public function setValues(values: Dynamic): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
