/**
IconSequence : generated by hxtern
*/
package google.maps;

class IconSequence{
	public function new();

	public var icon: google.maps.Symbol;

	public var offset: String;

	public var repeat: String;
}
