/**
KmlFeatureData : generated by hxtern
*/
package google.maps;

extern class KmlFeatureData {
	public function new() {}

	public var author: google.maps.KmlAuthor;

	public var description: String;

	public var id: String;

	public var infoWindowHtml: String;

	public var name: String;

	public var snippet: String;
}
