/**
LatLng : generated by hxtern
*/
package google.maps;

class LatLng{
	public function new(lat: Float, lng: Float, ?opt_noWrap: Bool);

	public function equals(other: google.maps.LatLng): Bool;

	public function lat(): Float;

	public function lng(): Float;

	public function toString(): String;

	public function toUrlValue(?opt_precision: Float): String;
}
