/**
MapCanvasProjection : generated by hxtern
*/
package google.maps;

class MapCanvasProjection{
	public function new();

	public function bindTo(key: String, target: google.maps.MVCObject, ?opt_targetKey: String, ?opt_noNotify: Bool): ;

	public function changed(key: String): ;

	public function fromContainerPixelToLatLng(pixel: google.maps.Point, ?opt_nowrap: Bool): google.maps.LatLng;

	public function fromDivPixelToLatLng(pixel: google.maps.Point, ?opt_nowrap: Bool): google.maps.LatLng;

	public function fromLatLngToContainerPixel(latLng: google.maps.LatLng): google.maps.Point;

	public function fromLatLngToDivPixel(latLng: google.maps.LatLng): google.maps.Point;

	public function get(key: String): Dynamic;

	public function getWorldWidth(): Float;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setValues(values: Dynamic): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
