/**
MarkerImage : generated by hxtern
*/
package google.maps;

class MarkerImage{
	public function new(url: String, ?opt_size: google.maps.Size, ?opt_origin: google.maps.Point, ?opt_anchor: google.maps.Point, ?opt_scaledSize: google.maps.Size);

	public var anchor: google.maps.Point;

	public var origin: google.maps.Point;

	public var scaledSize: google.maps.Size;

	public var size: google.maps.Size;

	public var url: String;
}
