/**
Symbol : generated by hxtern
*/
package google.maps;

class Symbol{
	public function new();

	public var anchor: google.maps.Point;

	public var fillColor: String;

	public var fillOpacity: Float;

	public var path: Dynamic;

	public var rotation: Float;

	public var scale: Float;

	public var strokeColor: String;

	public var strokeOpacity: Float;

	public var strokeWeight: Float;
}
