/**
  Weather : generated by hxtern
*/
package google.maps;
@:native("google.maps.weather")
extern class Weather {
	public static var LabelColor: Dynamic;

	public static var TemperatureUnit: Dynamic;

	public static var WindSpeedUnit: Dynamic;
}
