/**
  AdFormat : generated by hxtern
*/
package google.maps.adsense;

class AdFormat{
	public static var BANNER: Dynamic;

	public static var BUTTON: Dynamic;

	public static var HALF_BANNER: Dynamic;

	public static var LARGE_RECTANGLE: Dynamic;

	public static var LEADERBOARD: Dynamic;

	public static var MEDIUM_RECTANGLE: Dynamic;

	public static var SKYSCRAPER: Dynamic;

	public static var SMALL_RECTANGLE: Dynamic;

	public static var SMALL_SQUARE: Dynamic;

	public static var SQUARE: Dynamic;

	public static var VERTICAL_BANNER: Dynamic;

	public static var WIDE_SKYSCRAPER: Dynamic;
}
