/**
Manifest : generated by hxtern
Manifest information returned from chrome.runtime.getManifest. See
http://developer.chrome.com/extensions/manifest.html. Note that there are
several other fields not included here. They should be added to these externs
as needed.
*/
package chrome.runtime;

extern class Manifest {
	public function new() {}

	public var description: Hxtern.Any2<String,Null<Dynamic>>;

	public var manifest_version: Hxtern.Any2<Float,Null<Dynamic>>;

	public var name: String;

	public var oauth2: Hxtern.Any2<chrome.runtime.Manifest.Oauth2,Null<Dynamic>>;

	public var version: String;
}
