/**
MessageSenderEvent : generated by hxtern
Event whose listeners take a MessageSender and additional parameters.
*/
package chrome.runtime;

extern class MessageSenderEvent{
	public function new();

	public function addListener(_callback: Dynamic->MessageSender->Dynamic->Void->Hxtern.Any2<Bool,Null<Dynamic>>): Void {}

	public function hasListener(_callback: Dynamic->MessageSender->Dynamic->Void->Hxtern.Any2<Bool,Null<Dynamic>>): Bool {}

	public function hasListeners(): Bool {}

	public function removeListener(_callback: Dynamic->MessageSender->Dynamic->Void->Hxtern.Any2<Bool,Null<Dynamic>>): Void {}
}
