/**
ObjectEvent : generated by hxtern
Event whose listeners take an Object parameter.
*/
package chrome.runtime;

extern class ObjectEvent{
	public function new();

	public function addListener(_callback: Dynamic->Void): Void {}

	public function hasListener(_callback: Dynamic->Void): Bool {}

	public function hasListeners(): Bool {}

	public function removeListener(_callback: Dynamic->Void): Void {}
}
