/**
onRestartRequired : generated by hxtern
*/
package chrome.runtime;
@:native("chrome.runtime.onRestartRequired")
class OnRestartRequired{
	public function new();

	public function addListener(_callback: String->Void): Void;

	public function hasListener(_callback: String->Void): Bool;

	public function hasListeners(): Bool;

	public function removeListener(_callback: String->Void): Void;
}