/**
  DirectionsRoute : generated by hxtern
*/
package google.maps;

extern class DirectionsRoute {
	public function new() {}

	public var bounds: google.maps.LatLngBounds;

	public var copyrights: String;

	public var legs: Array<google.maps.DirectionsLeg>;

	public var overview_path: Array<google.maps.LatLng>;

	public var warnings: Array<String>;

	public var waypoint_order: Array<Float>;
}
