/**
  FusionTablesLayerOptions : generated by hxtern
*/
package google.maps;

extern class FusionTablesLayerOptions {
	public function new() {}

	public var clickable: Bool;

	public var heatmap: google.maps.FusionTablesHeatmap;

	public var map: google.maps.Map;

	public var query: google.maps.FusionTablesQuery;

	public var styles: Array<google.maps.FusionTablesStyle>;

	public var suppressInfoWindows: Bool;
}
