/**
KmlLayerMetadata : generated by hxtern
*/
package google.maps;

class KmlLayerMetadata{
	public function new();

	public var author: google.maps.KmlAuthor;

	public var description: String;

	public var hasScreenOverlays: Bool;

	public var name: String;

	public var snippet: String;
}
