/**
  KmlLayerOptions : generated by hxtern
*/
package google.maps;

extern class KmlLayerOptions {
	public function new() {}

	public var clickable: Bool;

	public var map: google.maps.Map;

	public var preserveViewport: Bool;

	public var screenOverlays: Bool;

	public var suppressInfoWindows: Bool;

	public var url: String;
}
