/**
  StreetViewPanoramaData : generated by hxtern
*/
package google.maps;

extern class StreetViewPanoramaData {
	public function new() {}

	public var copyright: String;

	public var imageDate: String;

	public var links: Array<google.maps.StreetViewLink>;

	public var location: google.maps.StreetViewLocation;

	public var tiles: google.maps.StreetViewTileData;
}
