/**
  TransitAgency : generated by hxtern
*/
package google.maps;

extern class TransitAgency {
	public function new() {}

	public var name: String;

	public var phone: String;

	public var url: String;
}
