/**
DrawingManager : generated by hxtern
*/
package google.maps.drawing;

class DrawingManager{
	public function new(?opt_options: hxtern.Any2<google.maps.drawing.DrawingManagerOptions,Dynamic<Dynamic>>);

	public function bindTo(key: String, target: google.maps.MVCObject, ?opt_targetKey: String, ?opt_noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function getDrawingMode(): google.maps.drawing.OverlayType;

	public function getMap(): google.maps.Map;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setDrawingMode(drawingMode: google.maps.drawing.OverlayType): ;

	public function setMap(map: google.maps.Map): ;

	public function setValues(values: hxtern.Any2<Dynamic,>): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
