/**
DrawingManagerOptions : generated by hxtern
*/
package google.maps.drawing;

extern class DrawingManagerOptions{
	public function new();

	public var circleOptions: Hxtern.Any2<google.maps.CircleOptions,Dynamic<Dynamic>>;

	public var drawingControl: Bool;

	public var drawingControlOptions: Hxtern.Any2<google.maps.drawing.DrawingControlOptions,Dynamic<Dynamic>>;

	public var drawingMode: google.maps.drawing.OverlayType;

	public var map: google.maps.Map;

	public var markerOptions: Hxtern.Any2<google.maps.MarkerOptions,Dynamic<Dynamic>>;

	public var polygonOptions: Hxtern.Any2<google.maps.PolygonOptions,Dynamic<Dynamic>>;

	public var polylineOptions: Hxtern.Any2<google.maps.PolylineOptions,Dynamic<Dynamic>>;

	public var rectangleOptions: Hxtern.Any2<google.maps.RectangleOptions,Dynamic<Dynamic>>;
}
