/**
  OverlayType : generated by hxtern
*/
package google.maps.drawing;

extern class OverlayType {
	public static var CIRCLE: Dynamic;

	public static var MARKER: Dynamic;

	public static var POLYGON: Dynamic;

	public static var POLYLINE: Dynamic;

	public static var RECTANGLE: Dynamic;
}
