/**
  DeviceEvent : generated by hxtern
*/
package chrome.mediaGalleriesPrivate;

class DeviceEvent{
	public function new();

	public function addListener(_callback: chrome.mediaGalleriesPrivate.DeviceCallback): Void;
}
