/**
SilverlightRuntimeErrorEventArgs : generated by hxtern
*/
package ;

extern class SilverlightRuntimeErrorEventArgs extends SilverlightErrorEventArgs {
	public function new() {}

	public var getHost: Dynamic;
}
