/**
SilverlightPlugin : generated by hxtern
*/
package ;

class SilverlightPlugin{
	public function new();

	public var framerate: Dynamic;

	public var ignoreBrowserVer: Dynamic;

	public var inplaceInstallPrompt: Dynamic;

	public var isWindowless: Dynamic;
}
