/**
SilverlightPlugin : generated by hxtern
*/
package ;

extern class SilverlightPlugin {
	public function new() {}

	public var framerate: Dynamic;

	public var ignoreBrowserVer: Dynamic;

	public var inplaceInstallPrompt: Dynamic;

	public var isWindowless: Dynamic;
}
