/**
SilverlightErrorEventArgs : generated by hxtern
*/
package ;

extern class SilverlightErrorEventArgs extends SilverlightDependencyObject {
	public function new() {}

	public var getHost: Dynamic;
}
