/**
SilverlightParserErrorEventArgs : generated by hxtern
*/
package ;

extern class SilverlightParserErrorEventArgs extends SilverlightErrorEventArgs {
	public function new() {}

	public var getHost: Dynamic;
}
