/**
  DistanceMatrixResponseRow : generated by hxtern
*/
package google.maps;

extern class DistanceMatrixResponseRow {
	public function new() {}

	public var elements: Array<google.maps.DistanceMatrixResponseElement>;
}
