/**
Geocoder : generated by hxtern
*/
package google.maps;

class Geocoder{
	public function new();

	public function geocode(request: hxtern.Any2<google.maps.GeocoderRequest,Dynamic<String>>, _callback: Array<google.maps.GeocoderResult>->google.maps.GeocoderStatus->Void): ;
}
