/**
PolyMouseEvent : generated by hxtern
*/
package google.maps;

class PolyMouseEvent{
	public function new();

	public var edge: Float;

	public var latLng: google.maps.LatLng;

	public var path: Float;

	public function stop(): ;

	public var vertex: Float;
}
