/**
  StrokePosition : generated by hxtern
*/
package google.maps;

class StrokePosition{
	public static var CENTER: Dynamic;

	public static var INSIDE: Dynamic;

	public static var OUTSIDE: Dynamic;
}
