/**
BlockingResponse : generated by hxtern
*/
package ;

class BlockingResponse{
	public function new();

	public var authCredentials: Dynamic<String>;

	public var cancel: Bool;

	public var redirectUrl: String;

	public var requestHeaders: HttpHeaders_;

	public var responseHeaders: HttpHeaders_;
}