/**
BookmarkTreeNode : generated by hxtern
*/
package ;

class BookmarkTreeNode{
	public function new();

	public var children: Array<BookmarkTreeNode>;

	public var dateAdded: Float;

	public var dateGroupModified: Float;

	public var id: String;

	public var index: Float;

	public var parentId: String;

	public var title: String;

	public var url: String;
}