/**
ChromeWindow : generated by hxtern
*/
package ;

class ChromeWindow{
	public function new();

	public var alwaysOnTop: Bool;

	public var focused: Bool;

	public var height: Float;

	public var id: Float;

	public var incognito: Bool;

	public var left: Float;

	public var state: String;

	public var tabs: Array<Tab>;

	public var top: Float;

	public var type: String;

	public var width: Float;
}