/**
ChromeSetting : generated by hxtern
*/
package ;

class ChromeSetting{
	public function new();

	public function clear(details: Dynamic, ?opt_callback: Void->Void): Void;

	public function get(details: Dynamic, _callback: Dynamic<Dynamic>->Void): Void;

	public function set(details: Dynamic, ?opt_callback: Void->Void): Void;
}