/**
ChromeInputImeOnKeyEventEvent : generated by hxtern
The OnKeyEvent event takes an extra argument.
*/
package ;

class ChromeInputImeOnKeyEventEvent{
	public function new();

	public function addListener(_callback: String->ChromeKeyboardEvent->Dynamic, ?opt_extraInfoSpec: Array<String>): Void;

	public function hasListener(_callback: String->ChromeKeyboardEvent->Dynamic): Void;

	public function hasListeners(_callback: String->ChromeKeyboardEvent->Dynamic): Void;

	public function removeListener(_callback: String->ChromeKeyboardEvent->Dynamic): Void;
}
