/**
ChromeKeyboardEvent : generated by hxtern
*/
package ;

extern class ChromeKeyboardEvent {
	public function new() {}

	public var altKey: Bool;

	public var ctrlKey: Bool;

	public var key: String;

	public var requestId: String;

	public var shiftKey: Bool;

	public var type: String;
}
