/**
ContentSetting : generated by hxtern
*/
package ;

extern class ContentSetting{
	public function new();

	public function clear(details: Dynamic<String>, ?opt_callback: Void->Void): Void {}

	public function get(detailsSettings: Dynamic<Hxtern.Any3<String,Bool,ResourceIdentifier>>, _callback: Void->Void): Void {}

	public function getResourceIdentifiers(_callback: Void->Void): Void {}

	public function set(detailsSettings: Dynamic<Hxtern.Any2<String,ResourceIdentifier>>, ?opt_callback: Void->Void): Void {}
}
