/**
Cookie : generated by hxtern
*/
package ;

class Cookie{
	public function new();

	public var domain: String;

	public var expirationDate: Float;

	public var hostOnly: Bool;

	public var httpOnly: Bool;

	public var name: String;

	public var path: String;

	public var secure: Bool;

	public var session: Bool;

	public var storeId: String;

	public var value: String;
}