/**
ExtensionInfo : generated by hxtern
onKeyEvent
*/
package ;

class ExtensionInfo{
	public function new();

	public var appLaunchUrl: String;

	public var description: String;

	public var disabledReason: String;

	public var enabled: Bool;

	public var homepageUrl: String;

	public var hostPermissions: Array<String>;

	public var icons: Array<IconInfo>;

	public var id: String;

	public var isApp: Bool;

	public var mayDisable: Bool;

	public var name: String;

	public var offlineEnabled: Bool;

	public var optionsUrl: String;

	public var permissions: Array<String>;

	public var updateUrl: String;

	public var version: String;
}