/**
FileHandlerExecuteEventDetails : generated by hxtern
*/
package ;

class FileHandlerExecuteEventDetails{
	public function new();

	public var entries: Array<FileEntry>;

	public var tab_id: Float;
}