/**
HttpHeader : generated by hxtern
*/
package ;

extern class HttpHeader {
	public function new() {}

	public var binaryValue: Array<Float>;

	public var name: String;

	public var value: String;
}
