/**
ProxyRules : generated by hxtern
*/
package ;

class ProxyRules{
	public function new();

	public var bypassList: Array<String>;

	public var fallbackProxy: ProxyServer;

	public var proxyForFtp: ProxyServer;

	public var proxyForHttp: ProxyServer;

	public var proxyForHttps: ProxyServer;

	public var singleProxy: ProxyServer;
}
