/**
ProxyConfig : generated by hxtern
*/
package ;

extern class ProxyConfig {
	public function new() {}

	public var mode: String;

	public var pacScript: PacScript;

	public var rules: ProxyRules;
}
