/**
RequestFilter : generated by hxtern
*/
package ;

extern class RequestFilter{
	public function new();

	public var tabId: Float;

	public var types: Array<String>;

	public var urls: Array<String>;

	public var windowId: Float;
}
