/**
StorageChangeEvent : generated by hxtern
The event listener for Storage receives an Object mapping each
key that changed to its corresponding StorageChange for that item.
*/
package ;

class StorageChangeEvent{
	public function new();

	public function addListener(_callback: Dynamic<StorageChange>->String->Void): Void;

	public function hasListener(_callback: Dynamic<StorageChange>->String->Void): Void;

	public function hasListeners(_callback: Dynamic<StorageChange>->String->Void): Void;

	public function removeListener(_callback: Dynamic<StorageChange>->String->Void): Void;
}