/**
StorageArea : generated by hxtern
*/
package ;

extern class StorageArea{
	public function new();

	public function clear(?opt_callback: Void->Void): Void {}

	public function get(?opt_keysA: Hxtern.Any4<String,Array<String>,Dynamic,?Dynamic>, ?opt_callback: Dynamic->Void): Void {}

	public function getBytesInUse(?opt_keysA: Hxtern.Any3<String,Array<String>,?Dynamic>, ?opt_callbackCallback: Float->Void): Void {}

	public function remove(keysA: Hxtern.Any2<String,Array<String>>, ?opt_callback: Void->Void): Void {}

	public function set(keysObject: Dynamic<String>, ?opt_callback: Void->Void): Void {}
}
