/**
Tab : generated by hxtern
*/
package ;

class Tab{
	public function new();

	public var active: Bool;

	public var favIconUrl: String;

	public var highlighted: Bool;

	public var id: Float;

	public var incognito: Bool;

	public var index: Float;

	public var openerTabId: Float;

	public var pinned: Bool;

	public var status: String;

	public var title: String;

	public var url: String;

	public var windowId: Float;
}
