/**
VisitItem : generated by hxtern
*/
package ;

extern class VisitItem{
	public function new();

	public var id: String;

	public var referringVisitId: String;

	public var transition: String;

	public var visitId: String;

	public var visitTime: Float;
}
