/**
WebRequestOnErrorOccurredEvent : generated by hxtern
The onErrorOccurred event takes one less parameter than the others.
*/
package ;

class WebRequestOnErrorOccurredEvent{
	public function new();

	public function addListener(listener: Dynamic->Void, filter: RequestFilter): Void;

	public function hasListener(listener: Dynamic->Void): Void;

	public function hasListeners(listener: Dynamic->Void): Void;

	public function removeListener(listener: Dynamic->Void): Void;
}