/**
AppWindow : generated by hxtern
*/
package chrome.app.window;

extern class AppWindow{
	public function new();

	public function clearAttention(): Void {}

	public function close(): Void {}

	public var contentWindow: Window;

	public function drawAttention(): Void {}

	public function focus(): Void {}

	public function fullscreen(): Void {}

	public function getBounds(): chrome.app.window.Bounds {}

	public function hide(): Void {}

	public function isAlwaysOnTop(): Bool {}

	public function isFullscreen(): Bool {}

	public function isMaximized(): Bool {}

	public function isMinimized(): Bool {}

	public function maximize(): Void {}

	public function minimize(): Void {}

	public function moveTo(left: Float, top: Float): Void {}

	public var onBoundsChanged: ChromeEvent;

	public var onClosed: ChromeEvent;

	public var onFullscreened: ChromeEvent;

	public var onMaximized: ChromeEvent;

	public var onMinimized: ChromeEvent;

	public var onRestored: ChromeEvent;

	public function resizeTo(width: Float, height: Float): Void {}

	public function restore(): Void {}

	public function setAlwaysOnTop(alwaysOnTop: Bool): Void {}

	public function setBounds(bounds: chrome.app.window.Bounds): Void {}

	public function show(): Void {}
}
