/**
  CreateWindowOptions : generated by hxtern
*/
package chrome.app.window;

extern typedef CreateWindowOptions = {id: Hxtern.Any2<String,Null<Dynamic>>, minWidth: Hxtern.Any2<Float,Null<Dynamic>>, minHeight: Hxtern.Any2<Float,Null<Dynamic>>, maxWidth: Hxtern.Any2<Float,Null<Dynamic>>, maxHeight: Hxtern.Any2<Float,Null<Dynamic>>, frame: Hxtern.Any2<String,Null<Dynamic>>, bounds: Hxtern.Any2<chrome.app.window.Bounds,Null<Dynamic>>, transparentBackground: Hxtern.Any2<Bool,Null<Dynamic>>, hidden: Hxtern.Any2<Bool,Null<Dynamic>>, resizable: Hxtern.Any2<Bool,Null<Dynamic>>, singleton: Hxtern.Any2<Bool,Null<Dynamic>>}

