/**
  DrawingControlOptions : generated by hxtern
*/
package google.maps.drawing;

class DrawingControlOptions{
	public function new();

	public var drawingModes: Array<google.maps.drawing.OverlayType>;

	public var position: google.maps.ControlPosition;
}
