/**
  Bookmarks : generated by hxtern
*/
package chrome;
@:native("chrome.bookmarks")
class Bookmarks{
	public static function create(bookmark: Dynamic, ?opt_callback: BookmarkTreeNode->Void): BookmarkTreeNode;

	public static function get(idOrIdList: String, _callback: Array<BookmarkTreeNode>->Void): Array<BookmarkTreeNode>;

	public static function getChildren(id: String, _callback: Array<BookmarkTreeNode>->Void): Array<BookmarkTreeNode>;

	public static function getRecent(numberOfItems: Float, _callback: Array<BookmarkTreeNode>->Void): Array<BookmarkTreeNode>;

	public static function getSubTree(id: String, _callback: Array<BookmarkTreeNode>->Void): Array<BookmarkTreeNode>;

	public static function getTree(_callback: Array<BookmarkTreeNode>->Void): Array<BookmarkTreeNode>;

	public static function move(id: String, destination: Dynamic, ?opt_callback: Array<BookmarkTreeNode>->Void): BookmarkTreeNode;

	public static var onChanged: ChromeEvent;

	public static var onChildrenReordered: ChromeEvent;

	public static var onCreated: ChromeEvent;

	public static var onImportBegan: ChromeEvent;

	public static var onImportEnded: ChromeEvent;

	public static var onMoved: ChromeEvent;

	public static var onRemoved: ChromeEvent;

	public static function remove(id: String, ?opt_callback: Void->Void): Void;

	public static function removeTree(id: String, ?opt_callback: Void->Void): Void;

	public static function search(query: String, _callback: Array<BookmarkTreeNode>->Void): Array<BookmarkTreeNode>;

	public static function update(id: String, changes: Dynamic, ?opt_callback: BookmarkTreeNode->Void): BookmarkTreeNode;
}