/**
  ContextMenus : generated by hxtern
*/
package chrome;
@:native("chrome.contextMenus")
class ContextMenus{
	public static function create(createProperties: Dynamic, ?opt_callback: Void->Void): Float;

	public static function remove(menuItemId: Float, ?opt_callback: Void->Void): Void;

	public static function removeAll(?opt_callback: Void->Void): Void;

	public static function update(id: Float, updateProperties: Dynamic, ?opt_callback: Void->Void): Void;
}
