/**
  Cookies : generated by hxtern
*/
package chrome;
@:native("chrome.cookies")
class Cookies{
	public static function get(details: Dynamic, _callback: Cookie->Void): Void;

	public static function getAll(details: Dynamic, _callback: Array<Cookie>->Void): Void;

	public static function getAllCookieStores(_callback: Array<CookieStore>->Void): Void;

	public static var onChanged: ChromeEvent;

	public static function remove(details: Dynamic): Void;

	public static function set(details: Dynamic): Void;
}
