/**
  FileSystem : generated by hxtern
*/
package chrome;
@:native("chrome.fileSystem")
class FileSystem{
	public static function chooseEntry(): Void;

	public static function getDisplayPath(entry: Entry, _callback: String->Void): Void;

	public static function getWriteableEntry(entry: Entry, _callback: Entry->Void): Void;

	public static function isRestorable(id: String, _callback: Bool->Void): Void;

	public static function isWritableEntry(entry: Entry, _callback: Bool->Void): Void;

	public static function restoreEntry(id: String, _callback: Entry->Void): Void;

	public static function retainEntry(entry: Entry): String;
}