/**
  I18n : generated by hxtern
*/
package chrome;
@:native("chrome.i18n")
extern class I18n {
	public static function getAcceptLanguages(_callback: Array<String>->Void): Void {}

	public static function getMessage(messageName: String, ?opt_args: Hxtern.Any2<String,Array<String>>): String {}
}
