/**
  I18n : generated by hxtern
*/
package chrome;
@:native("chrome.i18n")
class I18n{
	public static function getAcceptLanguages(_callback: Array<String>->Void): Void;

	public static function getMessage(messageName: String, ?opt_args: String): String;
}
