/**
  Idle : generated by hxtern
*/
package chrome;
@:native("chrome.idle")
class Idle{
	public static var onStateChanged: ChromeEvent;

	public static function queryState(thresholdSeconds: Float, _callback: String->Void): Void;

	public static function setDetectionInterval(intervalInSeconds: Float): Void;
}
