/**
Oauth2 : generated by hxtern
Oauth2 info in the manifest.
See http://developer.chrome.com/apps/app_identity.html#update_manifest.
*/

@:native("chrome.runtime.Manifest.Oauth2")
extern class Oauth2 {
	public function new() {}

	public var client_id: String;

	public var scopes: Array<String>;
}
