/**
  MediaGalleries : generated by hxtern
*/
package chrome;
class MediaGalleries{
	public static function getMediaFileSystemMetadata(mediaFileSystem: FileSystem): Void;

	public static function getMediaFileSystems(details: {interactive: String}, _callback: Array<FileSystem>->Void): Void;
}