/**
  MediaGalleries : generated by hxtern
*/
package chrome;
@:native("chrome.mediaGalleries")
class MediaGalleries{
	public static function getMediaFileSystemMetadata(mediaFileSystem: FileSystem): Void;

	public static function getMediaFileSystems(details: {interactive: Dynamic}, _callback: Array<FileSystem>->Void): Void;
}
