/**
  MusicManagerPrivate : generated by hxtern
*/
package chrome;
@:native("chrome.musicManagerPrivate")
extern class MusicManagerPrivate {
	public static function getDeviceId(_callback: String->Void): Void {}
}
