/**
  PageCapture : generated by hxtern
*/
package chrome;
@:native("chrome.pageCapture")
class PageCapture{
	public static function saveAsMHTML(details: Map<String, Float>, _callback: Blob->Void): Void;
}