/**
  PageAction : generated by hxtern
*/
package chrome;
class PageAction{
	public static function hide(tabId: Float): Void;

	public static var onClicked: ChromeEvent;

	public static function setIcon(details: Dynamic): Void;

	public static function setPopup(details: Dynamic): Void;

	public static function setTitle(details: Dynamic): Void;

	public static function show(tabId: Float): Void;
}