/**
  Privacy : generated by hxtern
*/
package chrome;
@:native("chrome.privacy")
class Privacy{
	public static var network: Map<String, ChromeSetting>;

	public static var services: Map<String, ChromeSetting>;

	public static var websites: Map<String, ChromeSetting>;
}