/**
  Privacy : generated by hxtern
*/
package chrome;
@:native("chrome.privacy")
extern class Privacy {
	public static var network: Dynamic<ChromeSetting>;

	public static var services: Dynamic<ChromeSetting>;

	public static var websites: Dynamic<ChromeSetting>;
}
