/**
  Proxy : generated by hxtern
*/
package chrome;
@:native("chrome.proxy")
extern class Proxy{
	public static var onProxyError: ChromeEvent;

	public static var settings: Dynamic<ChromeSetting>;
}
