/**
  PushMessaging : generated by hxtern
*/
package chrome;
class PushMessaging{
	public static function getChannelId(interactiveOrCallback: Bool, ?opt_callback: chrome.pushMessaging.ChannelIdResult->Void): Void;

	public static var onMessage: chrome.pushMessaging.PushMessageEvent;
}