/**
  Runtime : generated by hxtern
*/
package chrome;
@:native("chrome.runtime")
class Runtime{
	public static function connect(?opt_extensionIdOrConnectInfo: String, ?opt_connectInfo: Dynamic<String>): Port;

	public static function connectNative(application: String): Port;

	public static function getBackgroundPage(_callback: Window->Void): Void;

	public static function getManifest(): chrome.runtime.Manifest;

	public static function getPackageDirectoryEntry(_callback: DirectoryEntry->Void): Void;

	public static function getPlatformInfo(_callback: Dynamic->Void): Void;

	public static function getURL(path: String): String;

	public static var id: String;

	public static var lastError: Dynamic;

	public static var onConnect: chrome.runtime.PortEvent;

	public static var onConnectExternal: chrome.runtime.PortEvent;

	public static var onInstalled: chrome.runtime.ObjectEvent;

	public static var onMessage: chrome.runtime.MessageSenderEvent;

	public static var onMessageExternal: chrome.runtime.MessageSenderEvent;

	public static var onStartup: ChromeEvent;

	public static var onSuspend: ChromeEvent;

	public static var onSuspendCanceled: ChromeEvent;

	public static var onUpdateAvailable: chrome.runtime.ObjectEvent;

	public static function reload(): Void;

	public static function requestUpdateCheck(_callback: String->Dynamic->Void): Void;

	public static function restart(): Void;

	public static function sendMessage(extensionIdOrMessage: String, ?opt_messageOrCallback: Dynamic, ?opt_callback: Dynamic->Void): Void;

	public static function sendNativeMessage(application: String, message: Dynamic, ?opt_callback: Dynamic->Void): Void;

	public static function setUninstallUrl(url: String): Void;
}
