/**
  Storage : generated by hxtern
*/
package chrome;
class Storage{
	public static var local: StorageArea;

	public static var onChanged: StorageChangeEvent;

	public static var sync: StorageArea;
}