/**
  Tabs : generated by hxtern
*/
package chrome;
class Tabs{
	public static function captureVisibleTab(windowId: Float, options: Dynamic, _callback: String->Void): Void;

	public static function connect(tabId: Float, ?opt_connectInfo: Dynamic<String>): Void;

	public static function create(createProperties: Dynamic, ?opt_callback: Tab->Void): Void;

	public static function detectLanguage(tabId: Float, _callback: String->Void): Void;

	public static function executeScript(tabId: Float, details: Dynamic, ?opt_callback: Void->Void): Void;

	public static function get(tabId: Float, _callback: Tab->Void): Void;

	public static function getAllInWindow(windowId: Float, _callback: Array<Tab>->Void): Void;

	public static function getCurrent(_callback: Tab->Void): Void;

	public static function getSelected(windowId: Float, _callback: Tab->Void): Void;

	public static function highlight(highlightInfo: Map<String, Float>, _callback: Window->Void): Void;

	public static function insertCSS(tabId: Float, details: Dynamic, ?opt_callback: Void->Void): Void;

	public static function move(tabId: Float, moveProperties: Map<String, Float>, ?opt_callback: Tab->Void): Void;

	public static var onActivated: ChromeEvent;

	public static var onActiveChanged: ChromeEvent;

	public static var onAttached: ChromeEvent;

	public static var onCreated: ChromeEvent;

	public static var onDetached: ChromeEvent;

	public static var onHighlightChanged: ChromeEvent;

	public static var onMoved: ChromeEvent;

	public static var onRemoved: ChromeEvent;

	public static var onReplaced: ChromeEvent;

	public static var onSelectionChanged: ChromeEvent;

	public static var onUpdated: ChromeEvent;

	public static function query(queryInfo: Map<String, Float>, ?opt_callback: Array<Tab>->Void): Array<Tab>;

	public static function reload(?opt_tabId: Float, ?opt_reloadProperties: Map<String, Bool>, ?opt_callback: Void->Void): Void;

	public static function remove(tabIds: Float, ?opt_callback: Tab->Void): Void;

	public static function sendMessage(tabId: Float, request: Dynamic, ?opt_callback: Dynamic->Void): Void;

	public static function sendRequest(tabId: Float, request: Dynamic, ?opt_callback: Dynamic->Void): Void;

	public static function update(tabId: Float, updateProperties: Map<String, String>, ?opt_callback: Tab->Void): Void;
}