/**
  WebNavigation : generated by hxtern
*/
package chrome;
@:native("chrome.webNavigation")
extern class WebNavigation{
	public static function getAllFrames(details: Dynamic, callbackCallback: Array<Dynamic<Hxtern.Any3<Bool,Float,String>>>->Void): Void {}

	public static function getFrame(details: Dynamic, callbackCallback: Dynamic<Hxtern.Any2<Bool,String>>->Void): Void {}

	public static var onBeforeNavigate: ChromeEvent;

	public static var onCommitted: ChromeEvent;

	public static var onCompleted: ChromeEvent;

	public static var onCreatedNavigationTarget: ChromeEvent;

	public static var onDOMContentLoaded: ChromeEvent;

	public static var onErrorOccurred: ChromeEvent;

	public static var onReferenceFragmentUpdated: ChromeEvent;
}
