/**
PlaceSearchRequest : generated by hxtern
*/
package google.maps.places;

extern class PlaceSearchRequest{
	public function new();

	public var bounds: google.maps.LatLngBounds;

	public var keyword: String;

	public var location: google.maps.LatLng;

	public var name: String;

	public var radius: Float;

	public var rankBy: google.maps.places.RankBy;

	public var types: Array<String>;
}
