/**
SearchBox : generated by hxtern
*/
package google.maps.places;

class SearchBox{
	public function new(inputField: HTMLInputElement, ?opt_opts: google.maps.places.SearchBoxOptions);

	public function addListener(eventName: String, handler: Dynamic): google.maps.MapsEventListener;

	public function bindTo(key: String, target: google.maps.MVCObject, ?opt_targetKey: String, ?opt_noNotify: Bool): ;

	public function changed(key: String): ;

	public function get(key: String): Dynamic;

	public function getBounds(): google.maps.LatLngBounds;

	public function notify(key: String): ;

	public function set(key: String, value: Dynamic): ;

	public function setBounds(bounds: google.maps.LatLngBounds): ;

	public function setValues(values: Dynamic): ;

	public function unbind(key: String): ;

	public function unbindAll(): ;
}
