/**
Bounds : generated by hxtern
*/
package chrome.system.display;

class Bounds{
	public function new();

	public var height: Float;

	public var left: Float;

	public var top: Float;

	public var width: Float;
}