/**
DisplayInfo : generated by hxtern
*/
package chrome.system.display;

class DisplayInfo{
	public function new();

	public var bounds: chrome.system.display.Bounds;

	public var dpiX: Float;

	public var dpiY: Float;

	public var id: String;

	public var isEnabled: Bool;

	public var isInternal: Bool;

	public var isPrimary: Bool;

	public var mirroringSourceId: String;

	public var name: String;

	public var overscan: chrome.system.display.Insets;

	public var rotation: Float;

	public var workArea: chrome.system.display.Bounds;
}
