/**
  Insets : generated by hxtern
*/
package chrome.system.display;

extern typedef Insets = {left: Hxtern.Any2<Float,Null<Dynamic>>, top: Hxtern.Any2<Float,Null<Dynamic>>, right: Hxtern.Any2<Float,Null<Dynamic>>, bottom: Hxtern.Any2<Float,Null<Dynamic>>}

