/**
  Global : generated by hxtern
*/
package jquery;

class Global{
	public static function $(arg: hxtern.Any6<String,Node,Element,Array<Element>,Dynamic,Window>, ?opt_arg: hxtern.Any2<JQueryObject,Document>): JQueryObject;
}
