/**
WeightedLocation : generated by hxtern
*/
package google.maps.visualization;

class WeightedLocation{
	public function new();

	public var location: google.maps.LatLng;

	public var weight: Float;
}
