/**
  HeatmapLayerOptions : generated by hxtern
*/
package google.maps.visualization;

extern class HeatmapLayerOptions {
	public function new() {}

	public var data: google.maps.MVCArray<google.maps.LatLng>;

	public var dissipating: Bool;

	public var gradient: Array<String>;

	public var map: google.maps.Map;

	public var maxIntensity: Float;

	public var opacity: Float;

	public var radius: Float;
}
