/**
FileException : generated by hxtern
*/
package ;

class FileException{
	public function new();

	public static var ABORT_ERR: Float;

	public static var ENCODING_ERR: Float;

	public static var INVALID_MODIFICATION_ERR: Float;

	public static var INVALID_STATE_ERR: Float;

	public static var NO_MODIFICATION_ALLOWED_ERR: Float;

	public static var NOT_FOUND_ERR: Float;

	public static var NOT_READABLE_ERR: Float;

	public static var PATH_EXISTS_ERR: Float;

	public static var QUOTA_EXCEEDED_ERR: Float;

	public static var SECURITY_ERR: Float;

	public static var SYNTAX_ERR: Float;

	public static var TYPE_MISMATCH_ERR: Float;

	public var ABORT_ERR: Float;

	public var code: Float;

	public var ENCODING_ERR: Float;

	public var INVALID_MODIFICATION_ERR: Float;

	public var INVALID_STATE_ERR: Float;

	public var NO_MODIFICATION_ALLOWED_ERR: Float;

	public var NOT_FOUND_ERR: Float;

	public var NOT_READABLE_ERR: Float;

	public var PATH_EXISTS_ERR: Float;

	public var QUOTA_EXCEEDED_ERR: Float;

	public var SECURITY_ERR: Float;

	public var SYNTAX_ERR: Float;

	public var TYPE_MISMATCH_ERR: Float;
}
