/**
FileWriterSync : generated by hxtern
*/
package ;

class FileWriterSync{
	public function new();

	public function seek(offset: Float): Void {}

	public function truncate(size: Float): Void {}

	public function write(blob: Blob): Void {}
}
