/**
DeliveredIntent : generated by hxtern
*/
package ;
class DeliveredIntent{
	public function new();

	public var action: String;

	public var data: Dynamic;

	public function getExtra(key: String): String;

	public var ports: Array<MessagePort>;

	public function postFailure(result: Dynamic): Void;

	public function postResult(result: Dynamic): Void;

	public var type: String;
}