/**
HTMLIntentElement : generated by hxtern
*/
package ;

extern class HTMLIntentElement extends HTMLElement {
	public function new() {}

	public var action: String;

	public var disposition: String;

	public var href: String;

	public var title: String;

	public var type: String;
}
