/**
Intent : generated by hxtern
*/
package ;

class Intent{
	public function new(action: String, type: String, ?opt_data: Dynamic, ?opt_transferList: Array<Transferable>);

	public var action: String;

	public var data: Dynamic;

	public var type: String;
}
