/**
  Global : generated by hxtern
*/
package jquery;

class Global{
	public static function $(?arg1: hxtern.Any.Any6<JQuerySelector,js.html.Element,Array,Dynamic,String,Void->Void>, ?arg2: hxtern.Any.Any4<js.html.Element,JQueryObject,Document,Dynamic>): JQueryObject {}

	public static function jQuery(?arg1: hxtern.Any.Any6<JQuerySelector,js.html.Element,Array,Dynamic,String,Void->Void>, ?arg2: hxtern.Any.Any4<js.html.Element,JQueryObject,Document,Dynamic>): JQueryObject {}
}
