/**
  Global : generated by hxtern
*/
package jquery;

class Global{
	public static function $(?arg1: hxtern.Any6<JQuerySelector,Element,Array,Dynamic,String,Void->Void>, ?arg2: hxtern.Any4<Element,JQueryObject,Document,Dynamic>): JQueryObject;

	public static function jQuery(?arg1: hxtern.Any6<JQuerySelector,Element,Array,Dynamic,String,Void->Void>, ?arg2: hxtern.Any4<Element,JQueryObject,Document,Dynamic>): JQueryObject;
}
