/**
  Support : generated by hxtern
*/
package jQuery;
@:native("jQuery.support")
class Support{
	public static var boxModel: Bool;

	public static var changeBubbles: Bool;

	public static var cssFloat: Bool;

	public static var hrefNormalized: Bool;

	public static var htmlSerialize: Bool;

	public static var leadingWhitespace: Bool;

	public static var noCloneEvent: Bool;

	public static var opacity: Bool;

	public static var scriptEval: Bool;

	public static var style: Bool;

	public static var submitBubbles: Bool;

	public static var tbody: Bool;
}
