/**
  ResponseObject : generated by hxtern
*/
package gadgets.io;

class ResponseObject{
	public static var data: Dynamic;

	public static var errors: Array<String>;

	public static var headers: Dynamic;

	public static var oauthApprovalUrl: String;

	public static var oauthError: String;

	public static var oauthErrorText: String;

	public static var rc: Float;

	public static var text: String;
}
