/**
AdUnitOptions : generated by hxtern
*/
package google.maps.adsense;

class AdUnitOptions{
	public function new();

	public var channelNumber: String;

	public var format: google.maps.adsense.AdFormat;

	public var map: google.maps.Map;

	public var position: google.maps.ControlPosition;

	public var publisherId: String;
}
