/**
PlacesService : generated by hxtern
*/
package google.maps.places;

extern class PlacesService {
	public function new(attrContainer: Hxtern.Any2<HTMLDivElement,google.maps.Map>) {}

	public function getDetails(request: Hxtern.Any2<google.maps.places.PlaceDetailsRequest,Dynamic<String>>, _callback: google.maps.places.PlaceResult->google.maps.places.PlacesServiceStatus->Void): Null<Dynamic> {}

	public function nearbySearch(request: Hxtern.Any2<google.maps.places.PlaceSearchRequest,Dynamic<String>>, _callback: Array<google.maps.places.PlaceResult>->google.maps.places.PlacesServiceStatus->google.maps.places.PlaceSearchPagination->Void): Null<Dynamic> {}

	public function radarSearch(request: Hxtern.Any2<google.maps.places.RadarSearchRequest,Dynamic<String>>, _callback: Array<google.maps.places.PlaceResult>->google.maps.places.PlacesServiceStatus->Void): Null<Dynamic> {}

	public function textSearch(request: Hxtern.Any2<google.maps.places.TextSearchRequest,Dynamic<String>>, _callback: Array<google.maps.places.PlaceResult>->google.maps.places.PlacesServiceStatus->Void): Null<Dynamic> {}
}
