/**
  PlacesServiceStatus : generated by hxtern
*/
package google.maps.places;

extern class PlacesServiceStatus {
	public static var INVALID_REQUEST: Dynamic;

	public static var OK: Dynamic;

	public static var OVER_QUERY_LIMIT: Dynamic;

	public static var REQUEST_DENIED: Dynamic;

	public static var UNKNOWN_ERROR: Dynamic;

	public static var ZERO_RESULTS: Dynamic;
}
