/**
PlaceGeometry : generated by hxtern
*/
package google.maps.places;

extern class PlaceGeometry {
	public function new() {}

	public var location: google.maps.LatLng;

	public var viewport: google.maps.LatLngBounds;
}
