/**
  DemographicsStyle : generated by hxtern
*/
package google.maps.visualization;

class DemographicsStyle{
	public function new();

	public var polygonOptions: Dynamic;

	public var where: String;
}
