/**
  MapsEngineMouseEvent : generated by hxtern
*/
package google.maps.visualization;

extern class MapsEngineMouseEvent {
	public function new() {}

	public var featureId: String;

	public var infoWindowHtml: String;

	public var latLng: google.maps.LatLng;

	public var pixelOffset: google.maps.Size;
}
