/**
  MapsEngineStatus : generated by hxtern
*/
package google.maps.visualization;

extern class MapsEngineStatus {
	public static var INVALID_LAYER: Dynamic;

	public static var OK: Dynamic;

	public static var UNKNOWN_ERROR: Dynamic;
}
