/**
MapTypeStyle : generated by hxtern
*/
package google.maps;

extern class MapTypeStyle{
	public function new();

	public var elementType: google.maps.MapTypeStyleElementType;

	public var featureType: google.maps.MapTypeStyleFeatureType;

	public var stylers: Array<google.maps.MapTypeStyler>;
}
