/**
  StreetViewStatus : generated by hxtern
*/
package google.maps;

extern class StreetViewStatus {
	public static var OK: Dynamic;

	public static var UNKNOWN_ERROR: Dynamic;

	public static var ZERO_RESULTS: Dynamic;
}
