/**
  DemographicsStyle : generated by hxtern
*/
package google.maps.visualization;

class DemographicsStyle{
	public function new();

	public var polygonOptions: hxtern.Any2<google.maps.visualization.DemographicsPolygonOptions,Dynamic<String>>;

	public var where: String;
}
