/**
  DemographicsPropertyStyle : generated by hxtern
*/
package google.maps.visualization;

class DemographicsPropertyStyle{
	public function new();

	public var expression: String;

	public var gradient: Array<String>;

	public var max: Float;

	public var min: Float;
}
