/**
  DemographicsStyle : generated by hxtern
*/
package google.maps.visualization;

class DemographicsStyle{
	public function new();

	public var polygonOptions: google.maps.visualization.DemographicsPolygonOptions;

	public var where: String;
}
