/**
  Permissions : generated by hxtern
*/
package chrome.permissions;

extern typedef Permissions = {permissions: Hxtern.Any2<Array<String>,Null<Dynamic>>, origins: Hxtern.Any2<Array<String>,Null<Dynamic>>}

