/**
  Google : generated by hxtern
*/
package ;
class Google{
	public static function load(moduleName: String, moduleVersion: String, ?optionalSettings: Map<String, Dynamic>): Void;

	public static var loader: Dynamic;

	public static function setOnLoadCallback(_callback: Void->Void): Void;
}