/**
  Google : generated by hxtern
*/
package ;
@:native("google")
class Google{
	public static function load(moduleName: String, moduleVersion: String, ?optionalSettings: Dynamic<Dynamic>): Void;

	public static var loader: Dynamic;

	public static function setOnLoadCallback(_callback: Void->Void): Void;
}
