/**
Geocoder : generated by hxtern
*/
package google.maps;

class Geocoder{
	public function new();

	public function geocode(request: google.maps.GeocoderRequest, _callback: Array<google.maps.GeocoderResult>->google.maps.GeocoderStatus->Void): ;
}
