/**
  GeocoderRequest : generated by hxtern
*/
package google.maps;

extern class GeocoderRequest {
	public function new() {}

	public var address: String;

	public var bounds: google.maps.LatLngBounds;

	public var location: google.maps.LatLng;

	public var region: String;
}
