/**
GeocoderGeometry : generated by hxtern
*/
package google.maps;

extern class GeocoderGeometry {
	public function new() {}

	public var bounds: google.maps.LatLngBounds;

	public var location: google.maps.LatLng;

	public var location_type: google.maps.GeocoderLocationType;

	public var viewport: google.maps.LatLngBounds;
}
