/**
  GroundOverlayOptions : generated by hxtern
*/
package google.maps;

extern class GroundOverlayOptions {
	public function new() {}

	public var clickable: Bool;

	public var map: google.maps.Map;

	public var opacity: Float;
}
