/**
  MapTypeStyler : generated by hxtern
*/
package google.maps;

extern class MapTypeStyler {
	public function new() {}

	public var color: String;

	public var gamma: Float;

	public var hue: String;

	public var invert_lightness: Bool;

	public var lightness: Float;

	public var saturation: Float;

	public var visibility: String;

	public var weight: Float;
}
