/**
  PlacePhoto : generated by hxtern
*/
package google.maps.places;

extern class PlacePhoto {
	public function new() {}

	public function getUrl(opts: Hxtern.Any2<google.maps.places.PhotoOptions,Dynamic<String>>): String {}

	public var height: Float;

	public var html_attributions: Array<String>;

	public var width: Float;
}
